package com.logmng.service;

import com.logmng.dto.response.UserListItemResponse;
import com.logmng.exception.CustomException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Soft delete user, list filtering, system-admin guards (req 20260407). TC-01, TC-05–TC-07.
 */
class DecryptApproverServiceSoftDeleteTest {

    private static final String H2_URL = "jdbc:h2:mem:soft_delete_user_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;"
            + "DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH";

    private DataSource dataSource;
    private DecryptApproverService service;
    private AtomicReference<String> lastActionType;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = createH2();
        lastActionType = new AtomicReference<>();
        UserActivityLogService captureLog = new UserActivityLogService(dataSource, new com.logmng.repository.UserActivityAccessAuditRepository(dataSource)) {
            @Override
            public void saveActivityLog(String userId, String username, String actionType,
                                        java.util.Map<String, Object> actionDetail, String ipAddress,
                                        String userAgent, String requestMethod, String requestPath,
                                        String requestParams, Integer responseStatus,
                                        Integer responseTimeMs, Boolean success, String errorMessage) {
                lastActionType.set(actionType);
            }
        };
        AppUserResolver resolver = new AppUserResolver(dataSource);
        service = new DecryptApproverService(dataSource, new DepartmentService(dataSource), captureLog,
                new PermissionGroupService(dataSource, resolver), resolver);
        seed();
    }

    private static DataSource createH2() throws Exception {
        Class.forName("org.h2.Driver");
        try (Connection conn = java.sql.DriverManager.getConnection(H2_URL);
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS app_user_external_identity");
            stmt.execute("DROP TABLE IF EXISTS app_user");
            stmt.execute("DROP TABLE IF EXISTS department");
            stmt.execute("CREATE TABLE department (code VARCHAR(50) PRIMARY KEY)");
            stmt.execute("CREATE TABLE app_user ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "username VARCHAR(100) NOT NULL UNIQUE, "
                    + "password_hash VARCHAR(255) NOT NULL DEFAULT 'x', "
                    + "role VARCHAR(20) NOT NULL DEFAULT 'USER', "
                    + "department_code VARCHAR(50), "
                    + "position VARCHAR(100), "
                    + "rank VARCHAR(100), "
                    + "is_system_admin BOOLEAN NOT NULL DEFAULT false, "
                    + "employee_number VARCHAR(100), "
                    + "deleted_at TIMESTAMP NULL)");
            stmt.execute("CREATE TABLE app_user_external_identity ("
                    + "app_user_id BIGINT NOT NULL, "
                    + "source_system VARCHAR(64) NOT NULL, "
                    + "external_employee_id VARCHAR(256) NOT NULL, "
                    + "PRIMARY KEY (source_system, external_employee_id), "
                    + "FOREIGN KEY (app_user_id) REFERENCES app_user(id) ON DELETE CASCADE)");
        }
        org.h2.jdbcx.JdbcDataSource ds = new org.h2.jdbcx.JdbcDataSource();
        ds.setURL(H2_URL);
        return ds;
    }

    private void seed() throws Exception {
        try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("INSERT INTO department (code) VALUES ('D01')");
            stmt.execute("INSERT INTO app_user (username, password_hash, role, is_system_admin, employee_number) "
                    + "VALUES ('u_normal', 'x', 'USER', false, '20269901'), "
                    + "('u_admin', 'x', 'USER', true, NULL), "
                    + "('u_admin2', 'x', 'USER', true, NULL)");
        }
    }

    @Test
    @DisplayName("TC-01: listUsers returns employeeNumber from persisted row for active users")
    void listUsers_exposesEmployeeNumber() {
        List<UserListItemResponse> users = service.listUsers();
        UserListItemResponse u = users.stream().filter(r -> "u_normal".equals(r.getUsername())).findFirst().orElse(null);
        assertThat(u).isNotNull();
        assertThat(u.getEmployeeNumber()).isEqualTo("20269901");
    }

    @Test
    @DisplayName("TC-06: soft delete removes user from list and emits USER_DELETE")
    void softDelete_excludesFromList_andLogs() throws Exception {
        long id;
        try (Connection conn = dataSource.getConnection(); java.sql.PreparedStatement ps =
                     conn.prepareStatement("SELECT id FROM app_user WHERE username = 'u_normal'")) {
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                id = rs.getLong("id");
            }
        }

        service.softDeleteUserById(id, "offboarding test", "actor1", "127.0.0.1");

        assertThat(service.listUsers()).noneMatch(u -> "u_normal".equals(u.getUsername()));
        try (Connection conn = dataSource.getConnection(); java.sql.PreparedStatement ps =
                     conn.prepareStatement("SELECT deleted_at FROM app_user WHERE id = ?")) {
            ps.setLong(1, id);
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getTimestamp("deleted_at")).isNotNull();
            }
        }
        assertThat(lastActionType.get()).isEqualTo("USER_DELETE");
    }

    @Test
    @DisplayName("TC-05: blank changeReason → INVALID_INPUT")
    void softDelete_blankReason_throws() throws Exception {
        long id;
        try (Connection conn = dataSource.getConnection(); java.sql.PreparedStatement ps =
                     conn.prepareStatement("SELECT id FROM app_user WHERE username = 'u_normal'")) {
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                id = rs.getLong("id");
            }
        }
        assertThatThrownBy(() -> service.softDeleteUserById(id, "   ", "actor1", "127.0.0.1"))
                .isInstanceOf(CustomException.class)
                .hasFieldOrPropertyWithValue("errorCode", "INVALID_INPUT");
    }

    @Test
    @DisplayName("TC-07: only system admin → LAST_SYSTEM_ADMIN_BLOCKED")
    void softDelete_onlySystemAdmin_throwsLastAdmin() throws Exception {
        try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM app_user WHERE username = 'u_normal'");
            stmt.execute("DELETE FROM app_user WHERE username IN ('u_admin2')");
        }
        long id;
        try (Connection conn = dataSource.getConnection(); java.sql.PreparedStatement ps =
                     conn.prepareStatement("SELECT id FROM app_user WHERE username = 'u_admin'")) {
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                id = rs.getLong("id");
            }
        }
        assertThatThrownBy(() -> service.softDeleteUserById(id, "cannot delete last admin", "actor1", "127.0.0.1"))
                .isInstanceOf(CustomException.class)
                .hasFieldOrPropertyWithValue("errorCode", "LAST_SYSTEM_ADMIN_BLOCKED");
    }

    @Test
    @DisplayName("TC-07: system admin when another exists → SYSTEM_ADMIN_IMMUTABLE")
    void softDelete_systemAdminWhenPeerExists_throwsImmutable() throws Exception {
        long id;
        try (Connection conn = dataSource.getConnection(); java.sql.PreparedStatement ps =
                     conn.prepareStatement("SELECT id FROM app_user WHERE username = 'u_admin'")) {
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                id = rs.getLong("id");
            }
        }
        assertThatThrownBy(() -> service.softDeleteUserById(id, "try delete admin", "actor1", "127.0.0.1"))
                .isInstanceOf(CustomException.class)
                .hasFieldOrPropertyWithValue("errorCode", "SYSTEM_ADMIN_IMMUTABLE");
    }
}
