package com.logmng.service;

import com.logmng.dto.response.UserListItemResponse;
import com.logmng.exception.CustomException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * DecryptApproverService.updateUserRole unit tests. §7.4
 * Uses H2 in-memory DB for role update, self-demotion, last-admin edge cases.
 */
class DecryptApproverServiceUpdateRoleTest {

    private static final String H2_URL = "jdbc:h2:mem:update_role_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE";

    private DataSource dataSource;
    private DepartmentService departmentService;
    private DecryptApproverService decryptApproverService;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = createH2DataSource();
        departmentService = new DepartmentService(dataSource);
        AppUserResolver resolver = new AppUserResolver(dataSource);
        decryptApproverService = new DecryptApproverService(dataSource, departmentService, null,
                new PermissionGroupService(dataSource, resolver), resolver);
    }

    private static DataSource createH2DataSource() throws Exception {
        Class.forName("org.h2.Driver");
        try (Connection conn = java.sql.DriverManager.getConnection(H2_URL);
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS decrypt_approver");
            stmt.execute("DROP TABLE IF EXISTS app_user");
            stmt.execute("CREATE TABLE IF NOT EXISTS department (" +
                    "code VARCHAR(50) PRIMARY KEY, parent_code VARCHAR(50), name VARCHAR(200), sort_order INT DEFAULT 0)");
            stmt.execute("CREATE TABLE IF NOT EXISTS app_user (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(100) NOT NULL UNIQUE, " +
                    "password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, department_code VARCHAR(50), " +
                    "position VARCHAR(50), rank VARCHAR(50), is_system_admin BOOLEAN NOT NULL DEFAULT false, " +
                    "employee_number VARCHAR(100), deleted_at TIMESTAMP NULL)");
            stmt.execute("CREATE TABLE IF NOT EXISTS decrypt_approver (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id VARCHAR(100) NOT NULL, app_user_id BIGINT, department_code VARCHAR(50))");

            stmt.execute("DELETE FROM decrypt_approver");
            stmt.execute("DELETE FROM app_user");
            stmt.execute("DELETE FROM department");

            stmt.execute("INSERT INTO department (code, parent_code, name, sort_order) VALUES ('D1', NULL, 'Dept1', 0)");
            stmt.execute("INSERT INTO app_user (username, password_hash, role, department_code, is_system_admin) VALUES " +
                    "('admin1', 'hash', 'ADMIN', 'D1', true), " +
                    "('admin2', 'hash', 'ADMIN', 'D1', false), " +
                    "('user1', 'hash', 'USER', 'D1', false)");
        }
        org.h2.jdbcx.JdbcDataSource ds = new org.h2.jdbcx.JdbcDataSource();
        ds.setURL(H2_URL);
        return ds;
    }

    @Test
    void updateUserRole_whenValid_changesRoleAndReturnsUpdatedUser() {
        UserListItemResponse result = decryptApproverService.updateUserRole("admin1", "user1", "ADMIN");

        assertThat(result.getUserId()).isNotNull();
        assertThat(result.getUsername()).isEqualTo("user1");
        assertThat(result.getRole()).isEqualTo("ADMIN");

        UserListItemResponse after = decryptApproverService.updateUserRole("admin2", "user1", "USER");
        assertThat(after.getRole()).isEqualTo("USER");
    }

    @Test
    void updateUserRole_whenSelfDemotion_throws400() {
        assertThatThrownBy(() -> decryptApproverService.updateUserRole("admin1", "admin1", "USER"))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getErrorCode()).isEqualTo("SELF_DEMOTION_BLOCKED");
                    assertThat(ex.getHttpStatus().value()).isEqualTo(400);
                });
    }

    @Test
    void updateUserRole_whenSystemAdmin_throws400() {
        assertThatThrownBy(() -> decryptApproverService.updateUserRole("admin2", "admin1", "USER"))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getErrorCode()).isEqualTo("SYSTEM_ADMIN_IMMUTABLE");
                    assertThat(ex.getHttpStatus().value()).isEqualTo(400);
                });
    }

    @Test
    void updateUserRole_whenLastAdminDemotion_throws400() {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("UPDATE app_user SET is_system_admin = false WHERE username = 'admin1'");
            stmt.execute("DELETE FROM app_user WHERE username = 'admin2'");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        assertThatThrownBy(() -> decryptApproverService.updateUserRole("admin1", "admin1", "USER"))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getErrorCode()).isEqualTo("SELF_DEMOTION_BLOCKED");
                    assertThat(ex.getHttpStatus().value()).isEqualTo(400);
                });

        assertThatThrownBy(() -> decryptApproverService.updateUserRole("user1", "admin1", "USER"))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getErrorCode()).isEqualTo("LAST_ADMIN_BLOCKED");
                    assertThat(ex.getHttpStatus().value()).isEqualTo(400);
                });
    }

    @Test
    void updateUserRole_whenUserNotFound_throws404() {
        assertThatThrownBy(() -> decryptApproverService.updateUserRole("admin1", "nonexistent", "ADMIN"))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getErrorCode()).isEqualTo("USER_NOT_FOUND");
                    assertThat(ex.getHttpStatus().value()).isEqualTo(404);
                });
    }

    @Test
    void updateUserRole_whenInvalidRole_throws400() {
        assertThatThrownBy(() -> decryptApproverService.updateUserRole("admin1", "user1", "INVALID"))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getErrorCode()).isEqualTo("INVALID_INPUT");
                    assertThat(ex.getHttpStatus().value()).isEqualTo(400);
                });
    }

    @Test
    void updateUserRole_whenRoleBlank_throws400() {
        assertThatThrownBy(() -> decryptApproverService.updateUserRole("admin1", "user1", ""))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getErrorCode()).isEqualTo("INVALID_INPUT");
                });
    }

    @Test
    void updateUserRole_whenTwoAdmins_allowsDemotion() {
        UserListItemResponse result = decryptApproverService.updateUserRole("admin1", "admin2", "USER");
        assertThat(result.getRole()).isEqualTo("USER");
    }
}
