package com.logmng.service;

import com.logmng.dto.request.PermissionGroupCreateRequest;
import com.logmng.dto.response.AllowedScreenItem;
import com.logmng.exception.CustomException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Unit tests for PermissionGroupService (scope validation, default team).
 * Req: 20250304-team-scope-default-and-approval.
 */
class PermissionGroupServiceTest {

    private static final String H2_URL = "jdbc:h2:mem:perm_grp_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE";

    private DataSource dataSource;
    private PermissionGroupService service;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = createH2DataSource();
        service = new PermissionGroupService(dataSource);
    }

    private static DataSource createH2DataSource() throws Exception {
        Class.forName("org.h2.Driver");
        try (Connection conn = java.sql.DriverManager.getConnection(H2_URL);
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS permission_group (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(50) NOT NULL UNIQUE, " +
                    "name VARCHAR(200) NOT NULL, description VARCHAR(500), sort_order INT DEFAULT 0)");
            stmt.execute("CREATE TABLE IF NOT EXISTS permission_group_screen (" +
                    "permission_group_id BIGINT NOT NULL, screen_id VARCHAR(50) NOT NULL, " +
                    "scope VARCHAR(10), read BOOLEAN, write BOOLEAN, approve BOOLEAN, decrypt BOOLEAN, " +
                    "PRIMARY KEY (permission_group_id, screen_id))");
            stmt.execute("CREATE TABLE IF NOT EXISTS app_user_permission_group (" +
                    "user_id VARCHAR(100) NOT NULL, permission_group_id BIGINT NOT NULL, " +
                    "PRIMARY KEY (user_id, permission_group_id))");
        }
        org.h2.jdbcx.JdbcDataSource ds = new org.h2.jdbcx.JdbcDataSource();
        ds.setURL(H2_URL);
        return ds;
    }

    /**
     * TC-07: POST permission-groups with scope 'invalid' must return 400 (INVALID_INPUT).
     * Unit test: create() with allowedScreens containing a scope-supporting screen (activity-log)
     * and scope "invalid" throws CustomException with errorCode INVALID_INPUT and message
     * containing the scope validation text.
     */
    @Test
    void create_withInvalidScope_throwsInvalidInput() {
        PermissionGroupCreateRequest req = new PermissionGroupCreateRequest();
        req.setCode("pg1");
        req.setName("Test Group");
        AllowedScreenItem activityLog = new AllowedScreenItem();
        activityLog.setScreenId("activity-log");
        activityLog.setScope("invalid");
        req.setAllowedScreens(List.of(activityLog));

        assertThatThrownBy(() -> service.create(req))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getErrorCode()).isEqualTo("INVALID_INPUT");
                    assertThat(ex.getMessage()).contains("scope는 'self', 'team', 'all' 중 하나여야 합니다");
                    assertThat(ex.getMessage()).contains("invalid");
                });
    }

    /**
     * Valid scope 'team' for activity-log is accepted (no exception).
     */
    @Test
    void create_withValidScopeTeam_storesSuccessfully() {
        PermissionGroupCreateRequest req = new PermissionGroupCreateRequest();
        req.setCode("pg_team");
        req.setName("Team Scope Group");
        AllowedScreenItem activityLog = new AllowedScreenItem();
        activityLog.setScreenId("activity-log");
        activityLog.setScope("team");
        req.setAllowedScreens(List.of(activityLog));

        var response = service.create(req);
        assertThat(response).isNotNull();
        assertThat(response.getCode()).isEqualTo("pg_team");
        assertThat(response.getAllowedScreens()).hasSize(1);
        assertThat(response.getAllowedScreens().get(0).getScreenId()).isEqualTo("activity-log");
        assertThat(response.getAllowedScreens().get(0).getScope()).isEqualTo("team");
    }

    /**
     * TC-02 coverage: search-history with scope=team and approve=true (APPROVE_USER-like) is accepted and persisted.
     * Req: 20260304-permission-group-modal-error-visibility (Part 2).
     */
    @Test
    void create_withSearchHistoryScopeTeamAndApprove_storesSuccessfully() {
        PermissionGroupCreateRequest req = new PermissionGroupCreateRequest();
        req.setCode("approve_team");
        req.setName("Approve User Team");
        AllowedScreenItem searchHistory = new AllowedScreenItem();
        searchHistory.setScreenId("search-history");
        searchHistory.setScope("team");
        searchHistory.setApprove(true);
        req.setAllowedScreens(List.of(searchHistory));

        var response = service.create(req);
        assertThat(response).isNotNull();
        assertThat(response.getCode()).isEqualTo("approve_team");
        assertThat(response.getAllowedScreens()).hasSize(1);
        AllowedScreenItem item = response.getAllowedScreens().get(0);
        assertThat(item.getScreenId()).isEqualTo("search-history");
        assertThat(item.getScope()).isEqualTo("team");
        assertThat(item.getApprove()).isTrue();
    }

    /**
     * TC-05: Create permission group with search-history, approve=true, scope=self → stored row has scope='team'.
     * Req: 20260306-approval-scope-fixed-department.
     */
    @Test
    void create_searchHistoryApproveTrueScopeSelf_storedScopeIsTeam() throws Exception {
        PermissionGroupCreateRequest req = new PermissionGroupCreateRequest();
        req.setCode("pg_approve_self");
        req.setName("Approve Self Coerced");
        AllowedScreenItem searchHistory = new AllowedScreenItem();
        searchHistory.setScreenId("search-history");
        searchHistory.setScope("self");
        searchHistory.setApprove(true);
        req.setAllowedScreens(List.of(searchHistory));

        var response = service.create(req);
        assertThat(response).isNotNull();
        assertThat(response.getAllowedScreens()).hasSize(1);
        assertThat(response.getAllowedScreens().get(0).getScreenId()).isEqualTo("search-history");
        assertThat(response.getAllowedScreens().get(0).getScope()).isEqualTo("team");
        assertThat(response.getAllowedScreens().get(0).getApprove()).isTrue();

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT scope FROM permission_group_screen WHERE permission_group_id = ? AND screen_id = 'search-history'")) {
            ps.setLong(1, response.getId());
            try (var rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("scope")).isEqualTo("team");
            }
        }
    }

    /**
     * TC-06: Create permission group with pending-approvals, approve=true, scope=all → stored row has scope='team'.
     * Req: 20260306-approval-scope-fixed-department.
     */
    @Test
    void create_pendingApprovalsApproveTrueScopeAll_storedScopeIsTeam() throws Exception {
        PermissionGroupCreateRequest req = new PermissionGroupCreateRequest();
        req.setCode("pg_approve_all");
        req.setName("Approve All Coerced");
        AllowedScreenItem pendingApprovals = new AllowedScreenItem();
        pendingApprovals.setScreenId("pending-approvals");
        pendingApprovals.setScope("all");
        pendingApprovals.setApprove(true);
        req.setAllowedScreens(List.of(pendingApprovals));

        var response = service.create(req);
        assertThat(response).isNotNull();
        assertThat(response.getAllowedScreens()).hasSize(1);
        assertThat(response.getAllowedScreens().get(0).getScreenId()).isEqualTo("pending-approvals");
        assertThat(response.getAllowedScreens().get(0).getScope()).isEqualTo("team");
        assertThat(response.getAllowedScreens().get(0).getApprove()).isTrue();

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT scope FROM permission_group_screen WHERE permission_group_id = ? AND screen_id = 'pending-approvals'")) {
            ps.setLong(1, response.getId());
            try (var rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("scope")).isEqualTo("team");
            }
        }
    }

    /**
     * TC-04: getScreenScopesForUser returns pending-approvals scope when user has that screen with scope in permission group.
     * Req: 20260305-pending-approvals-scope-same-as-search-history.
     */
    @Test
    void getScreenScopesForUser_includesPendingApprovalsScopeWhenConfigured() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("INSERT INTO permission_group (id, code, name, description, sort_order) VALUES (100, 'pg_pending', 'Pending Scope', NULL, 0)");
            stmt.executeUpdate("INSERT INTO permission_group_screen (permission_group_id, screen_id, scope, read, write, approve, decrypt) VALUES (100, 'pending-approvals', 'team', true, false, true, NULL)");
        }
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO app_user_permission_group (user_id, permission_group_id) VALUES (?, ?)")) {
            ps.setString(1, "testuser");
            ps.setLong(2, 100L);
            ps.executeUpdate();
        }

        Map<String, String> scopes = service.getScreenScopesForUser("testuser");

        assertThat(scopes).containsEntry("pending-approvals", "team");
    }
}
