package com.logmng.service;

import com.logmng.config.AuthProperties;
import com.logmng.dto.request.ExternalEmployeeSearchRequest;
import com.logmng.dto.response.ExternalEmployeeItemResponse;
import com.logmng.dto.response.ExternalEmployeeSearchResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * {@link ProvisioningService#searchExternalEmployees} against H2 (PostgreSQL mode): JOIN ext_department,
 * departmentName / keyword / employeeNumber filters, count alignment.
 */
class ProvisioningServiceTest {

    private static final String H2_URL = "jdbc:h2:mem:provisioning_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;"
            + "DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH";

    private DataSource dataSource;
    private ProvisioningService provisioningService;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = createH2DataSource();
        provisioningService = new ProvisioningService(dataSource, new AuthProperties(), null, false);
        seed();
    }

    private static DataSource createH2DataSource() throws Exception {
        Class.forName("org.h2.Driver");
        try (Connection conn = java.sql.DriverManager.getConnection(H2_URL);
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS app_user_external_identity");
            stmt.execute("DROP TABLE IF EXISTS app_user");
            stmt.execute("DROP TABLE IF EXISTS ext_employee");
            stmt.execute("DROP TABLE IF EXISTS ext_department");
            stmt.execute("CREATE TABLE app_user ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "username VARCHAR(100) NOT NULL UNIQUE, "
                    + "password_hash VARCHAR(255) NOT NULL DEFAULT 'x', "
                    + "role VARCHAR(20) NOT NULL DEFAULT 'USER', "
                    + "is_system_admin BOOLEAN NOT NULL DEFAULT false, "
                    + "employee_number VARCHAR(100), "
                    + "deleted_at TIMESTAMP NULL, "
                    + "CONSTRAINT chk_app_user_role CHECK (role IN ('ADMIN', 'USER')))");
            stmt.execute("CREATE TABLE app_user_external_identity ("
                    + "app_user_id BIGINT NOT NULL, "
                    + "source_system VARCHAR(64) NOT NULL, "
                    + "external_employee_id VARCHAR(256) NOT NULL, "
                    + "PRIMARY KEY (source_system, external_employee_id), "
                    + "FOREIGN KEY (app_user_id) REFERENCES app_user(id) ON DELETE CASCADE)");
            stmt.execute("CREATE TABLE ext_department ("
                    + "source_system VARCHAR(64) NOT NULL, "
                    + "external_department_id VARCHAR(256) NOT NULL, "
                    + "name VARCHAR(500), "
                    + "PRIMARY KEY (source_system, external_department_id))");
            stmt.execute("CREATE TABLE ext_employee ("
                    + "source_system VARCHAR(64) NOT NULL, "
                    + "external_employee_id VARCHAR(256) NOT NULL, "
                    + "employee_number VARCHAR(100), "
                    + "display_name VARCHAR(500), "
                    + "job_title VARCHAR(200), "
                    + "external_department_id VARCHAR(256), "
                    + "PRIMARY KEY (source_system, external_employee_id))");
        }
        org.h2.jdbcx.JdbcDataSource ds = new org.h2.jdbcx.JdbcDataSource();
        ds.setURL(H2_URL);
        return ds;
    }

    private void seed() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM app_user_external_identity");
            stmt.execute("DELETE FROM app_user");
            stmt.execute("DELETE FROM ext_employee");
            stmt.execute("DELETE FROM ext_department");
            stmt.execute("INSERT INTO ext_department (source_system, external_department_id, name) VALUES "
                    + "('AD', 'D1', '영업본부'), ('AD', 'D2', '개발팀')");
            stmt.execute("INSERT INTO ext_employee (source_system, external_employee_id, employee_number, "
                    + "display_name, job_title, external_department_id) VALUES "
                    + "('AD', 'E1', '20261001', '김철수', 'MGR', 'D1'), "
                    + "('AD', 'E2', '20261002', '이영희', 'DEV', 'D2'), "
                    + "('AD', 'E3', '20261003', '박민수', 'STF', 'D1')");
            stmt.execute("INSERT INTO app_user (username, password_hash, role, is_system_admin) "
                    + "VALUES ('linked_user', 'x', 'USER', false)");
            stmt.execute("INSERT INTO app_user_external_identity (app_user_id, source_system, external_employee_id) "
                    + "VALUES (1, 'AD', 'E2')");
        }
    }

    @Test
    @DisplayName("departmentName filters by ext_department.name (ILIKE) and returns departmentName on items")
    void searchByDepartmentName() {
        ExternalEmployeeSearchRequest req = new ExternalEmployeeSearchRequest();
        req.setDepartmentName("영업");
        req.setPage(1);
        req.setPageSize(20);

        ExternalEmployeeSearchResult result = provisioningService.searchExternalEmployees(req);

        assertThat(result.getPagination().getTotalCount()).isEqualTo(2);
        assertThat(result.getItems()).hasSize(2);
        assertThat(result.getItems()).extracting(ExternalEmployeeItemResponse::getExternalEmployeeId)
                .containsExactlyInAnyOrder("E1", "E3");
        assertThat(result.getItems()).allMatch(i -> "영업본부".equals(i.getDepartmentName()));
        assertThat(result.getItems()).allMatch(i -> !i.isProvisioned());
    }

    @Test
    @DisplayName("keyword filters display_name (직원명)")
    void searchByKeyword() {
        ExternalEmployeeSearchRequest req = new ExternalEmployeeSearchRequest();
        req.setKeyword("이영희");
        req.setPage(1);
        req.setPageSize(20);

        ExternalEmployeeSearchResult result = provisioningService.searchExternalEmployees(req);

        assertThat(result.getPagination().getTotalCount()).isEqualTo(1);
        assertThat(result.getItems()).hasSize(1);
        assertThat(result.getItems().get(0).getExternalEmployeeId()).isEqualTo("E2");
        assertThat(result.getItems().get(0).getDepartmentName()).isEqualTo("개발팀");
        ExternalEmployeeItemResponse e2 = result.getItems().get(0);
        assertThat(e2.isProvisioned()).isTrue();
        assertThat(e2.getProvisionedUsername()).isEqualTo("linked_user");
        assertThat(e2.getProvisionedAppUserId()).isEqualTo(1L);
    }

    @Test
    @DisplayName("employeeNumber uses prefix LIKE on e.employee_number")
    void searchByEmployeeNumberPrefix() {
        ExternalEmployeeSearchRequest req = new ExternalEmployeeSearchRequest();
        req.setEmployeeNumber("20261");
        req.setPage(1);
        req.setPageSize(20);

        ExternalEmployeeSearchResult result = provisioningService.searchExternalEmployees(req);

        assertThat(result.getPagination().getTotalCount()).isEqualTo(3);
        assertThat(result.getItems()).hasSize(3);
    }

    @Test
    @DisplayName("employeeNumber is trimmed for LIKE; whitespace-only skips filter")
    void searchByEmployeeNumberTrimAndBlankSkips() {
        ExternalEmployeeSearchRequest spaced = new ExternalEmployeeSearchRequest();
        spaced.setEmployeeNumber("  20261  ");
        spaced.setPage(1);
        spaced.setPageSize(20);
        assertThat(provisioningService.searchExternalEmployees(spaced).getPagination().getTotalCount()).isEqualTo(3);

        ExternalEmployeeSearchRequest blank = new ExternalEmployeeSearchRequest();
        blank.setEmployeeNumber("  \t  ");
        blank.setPage(1);
        blank.setPageSize(20);
        assertThat(provisioningService.searchExternalEmployees(blank).getPagination().getTotalCount()).isEqualTo(3);
    }

    @Test
    @DisplayName("departmentName + keyword combined; count matches list")
    void searchCombinedDepartmentNameAndKeyword() {
        ExternalEmployeeSearchRequest req = new ExternalEmployeeSearchRequest();
        req.setDepartmentName("영업");
        req.setKeyword("박");
        req.setPage(1);
        req.setPageSize(20);

        ExternalEmployeeSearchResult result = provisioningService.searchExternalEmployees(req);

        assertThat(result.getPagination().getTotalCount()).isEqualTo(1);
        assertThat(result.getItems()).hasSize(1);
        assertThat(result.getItems().get(0).getExternalEmployeeId()).isEqualTo("E3");
        assertThat(result.getItems().get(0).getDepartmentName()).isEqualTo("영업본부");
        assertThat(result.getItems().get(0).isProvisioned()).isFalse();
    }

    @Test
    @DisplayName("LEFT JOIN app_user_external_identity: unprovisioned rows have provisioned false")
    void searchMarksUnprovisionedEmployees() {
        ExternalEmployeeSearchRequest req = new ExternalEmployeeSearchRequest();
        req.setKeyword("김철수");
        req.setSourceSystem("AD");
        req.setPage(1);
        req.setPageSize(20);

        ExternalEmployeeSearchResult result = provisioningService.searchExternalEmployees(req);

        assertThat(result.getItems()).hasSize(1);
        ExternalEmployeeItemResponse row = result.getItems().get(0);
        assertThat(row.isProvisioned()).isFalse();
        assertThat(row.getProvisionedUsername()).isNull();
        assertThat(row.getProvisionedAppUserId()).isNull();
    }

    @Test
    @DisplayName("TC-02: mapping to soft-deleted app_user → provisioned false")
    void provisionedFalseWhenMappedAppUserIsSoftDeleted() throws Exception {
        try (Connection conn = dataSource.getConnection();
             java.sql.Statement stmt = conn.createStatement()) {
            stmt.execute("UPDATE app_user SET deleted_at = CURRENT_TIMESTAMP WHERE id = 1");
        }
        ExternalEmployeeSearchRequest req = new ExternalEmployeeSearchRequest();
        req.setKeyword("이영희");
        req.setSourceSystem("AD");
        req.setPage(1);
        req.setPageSize(20);

        ExternalEmployeeSearchResult result = provisioningService.searchExternalEmployees(req);

        assertThat(result.getItems()).hasSize(1);
        ExternalEmployeeItemResponse row = result.getItems().get(0);
        assertThat(row.isProvisioned()).isFalse();
        assertThat(row.getProvisionedAppUserId()).isNull();
    }
}
