package com.logmng.service;

import com.logmng.config.AuthProperties;
import com.logmng.dto.request.ProvisionFromExternalEmployeeRequest;
import com.logmng.exception.CustomException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * {@link ProvisioningService#provisionFromExternalEmployee}: H2 (PostgreSQL mode),
 * {@code department_org_link} resolution when {@code departmentCode} is omitted.
 */
class ProvisioningServiceProvisionFromExternalEmployeeTest {

    private static final String H2_URL = "jdbc:h2:mem:provisioning_provision_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;"
            + "DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH";

    private DataSource dataSource;
    private ProvisioningService provisioningService;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = createH2DataSource();
        AuthProperties auth = new AuthProperties();
        auth.getProvisioning().setDefaultSourceSystem("AD");
        provisioningService = new ProvisioningService(dataSource, auth, null, false);
        seed();
    }

    private static DataSource createH2DataSource() throws Exception {
        Class.forName("org.h2.Driver");
        try (Connection conn = java.sql.DriverManager.getConnection(H2_URL);
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS app_user_external_identity");
            stmt.execute("DROP TABLE IF EXISTS app_user");
            stmt.execute("DROP TABLE IF EXISTS department_org_link");
            stmt.execute("DROP TABLE IF EXISTS ext_employee");
            stmt.execute("DROP TABLE IF EXISTS ext_department");
            stmt.execute("DROP TABLE IF EXISTS department");
            stmt.execute("CREATE TABLE department (code VARCHAR(50) PRIMARY KEY)");
            stmt.execute("CREATE TABLE ext_department ("
                    + "source_system VARCHAR(64) NOT NULL, "
                    + "external_department_id VARCHAR(256) NOT NULL, "
                    + "name VARCHAR(500), "
                    + "PRIMARY KEY (source_system, external_department_id))");
            stmt.execute("CREATE TABLE ext_employee ("
                    + "source_system VARCHAR(64) NOT NULL, "
                    + "external_employee_id VARCHAR(256) NOT NULL, "
                    + "employee_number VARCHAR(100), "
                    + "display_name VARCHAR(500), "
                    + "job_title VARCHAR(200), "
                    + "external_department_id VARCHAR(256), "
                    + "PRIMARY KEY (source_system, external_employee_id))");
            stmt.execute("CREATE TABLE department_org_link ("
                    + "source_system VARCHAR(64) NOT NULL, "
                    + "external_department_id VARCHAR(256) NOT NULL, "
                    + "department_code VARCHAR(50) NOT NULL, "
                    + "PRIMARY KEY (source_system, external_department_id), "
                    + "FOREIGN KEY (department_code) REFERENCES department(code) ON DELETE RESTRICT)");
            stmt.execute("CREATE TABLE app_user ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "username VARCHAR(100) NOT NULL UNIQUE, "
                    + "password_hash VARCHAR(255) NOT NULL, "
                    + "role VARCHAR(20) NOT NULL, "
                    + "department_code VARCHAR(50), "
                    + "name VARCHAR(200), "
                    + "employee_number VARCHAR(100), "
                    + "is_system_admin BOOLEAN NOT NULL DEFAULT false, "
                    + "deleted_at TIMESTAMP NULL, "
                    + "FOREIGN KEY (department_code) REFERENCES department(code) ON DELETE SET NULL, "
                    + "CONSTRAINT chk_app_user_role CHECK (role IN ('ADMIN', 'USER')))");
            stmt.execute("CREATE TABLE app_user_external_identity ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "app_user_id BIGINT NOT NULL, "
                    + "source_system VARCHAR(64) NOT NULL, "
                    + "external_employee_id VARCHAR(256) NOT NULL, "
                    + "CONSTRAINT fk_auei_user FOREIGN KEY (app_user_id) REFERENCES app_user(id) ON DELETE CASCADE, "
                    + "CONSTRAINT uq_auei_natural UNIQUE (source_system, external_employee_id))");
        }
        org.h2.jdbcx.JdbcDataSource ds = new org.h2.jdbcx.JdbcDataSource();
        ds.setURL(H2_URL);
        return ds;
    }

    private void seed() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM app_user_external_identity");
            stmt.execute("DELETE FROM app_user");
            stmt.execute("DELETE FROM department_org_link");
            stmt.execute("DELETE FROM ext_employee");
            stmt.execute("DELETE FROM ext_department");
            stmt.execute("DELETE FROM department");
            stmt.execute("INSERT INTO department (code) VALUES ('DEPT_FROM_LINK'), ('DEPT_FROM_REQ')");
            stmt.execute("INSERT INTO ext_employee (source_system, external_employee_id, employee_number, "
                    + "display_name, job_title, external_department_id) VALUES "
                    + "('AD', 'E_ORG', '20262001', '조직매핑', 'MGR', 'EXTD1'), "
                    + "('AD', 'E_NOMAP', '20262002', '매핑없음', 'STF', 'EXTD99')");
            stmt.execute("INSERT INTO department_org_link (source_system, external_department_id, department_code) "
                    + "VALUES ('AD', 'EXTD1', 'DEPT_FROM_LINK')");
        }
    }

    @Test
    @DisplayName("omit departmentCode: uses department_org_link for ext external_department_id")
    void provisionUsesOrgLinkWhenDepartmentCodeOmitted() {
        ProvisionFromExternalEmployeeRequest req = new ProvisionFromExternalEmployeeRequest();
        req.setExternalEmployeeId("E_ORG");
        req.setSourceSystem("AD");
        req.setChangeReason("조직 테스트 등록 사유");

        provisioningService.provisionFromExternalEmployee(req, "admin", "127.0.0.1", "JUnit");

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT department_code, employee_number FROM app_user WHERE name = '조직매핑'")) {
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("department_code")).isEqualTo("DEPT_FROM_LINK");
                assertThat(rs.getString("employee_number")).isEqualTo("20262001");
            }
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }

    @Test
    @DisplayName("employee_number from ext_employee is trimmed; blank/null stored as SQL NULL")
    void provisionTrimsEmployeeNumberAndStoresNullWhenBlank() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("INSERT INTO ext_employee (source_system, external_employee_id, employee_number, display_name, job_title, external_department_id) "
                    + "VALUES ('AD', 'E_TRIM', '  20269999  ', '트림테스트', 'STF', NULL), "
                    + "('AD', 'E_NONUM', NULL, '무사번', 'STF', NULL)");
        }

        ProvisionFromExternalEmployeeRequest reqTrim = new ProvisionFromExternalEmployeeRequest();
        reqTrim.setExternalEmployeeId("E_TRIM");
        reqTrim.setSourceSystem("AD");
        reqTrim.setDepartmentCode("DEPT_FROM_REQ");
        reqTrim.setChangeReason("트림 테스트");
        provisioningService.provisionFromExternalEmployee(reqTrim, "admin", "127.0.0.1", "JUnit");
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT employee_number FROM app_user WHERE name = '트림테스트'")) {
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("employee_number")).isEqualTo("20269999");
            }
        }

        ProvisionFromExternalEmployeeRequest reqNo = new ProvisionFromExternalEmployeeRequest();
        reqNo.setExternalEmployeeId("E_NONUM");
        reqNo.setSourceSystem("AD");
        reqNo.setDepartmentCode("DEPT_FROM_REQ");
        reqNo.setChangeReason("무사번 테스트");
        provisioningService.provisionFromExternalEmployee(reqNo, "admin", "127.0.0.1", "JUnit");
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT employee_number FROM app_user WHERE name = '무사번'")) {
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getObject("employee_number")).isNull();
            }
        }
    }

    @Test
    @DisplayName("explicit departmentCode wins over department_org_link")
    void provisionRequestDepartmentCodeOverridesLink() {
        ProvisionFromExternalEmployeeRequest req = new ProvisionFromExternalEmployeeRequest();
        req.setExternalEmployeeId("E_ORG");
        req.setSourceSystem("AD");
        req.setDepartmentCode("DEPT_FROM_REQ");
        req.setChangeReason("요청 부서 우선");

        provisioningService.provisionFromExternalEmployee(req, "admin", "127.0.0.1", "JUnit");

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT department_code FROM app_user WHERE name = '조직매핑'")) {
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("department_code")).isEqualTo("DEPT_FROM_REQ");
            }
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }

    @Test
    @DisplayName("no departmentCode and no org link row: app_user.department_code is null")
    void provisionLeavesDepartmentNullWhenNoLink() {
        ProvisionFromExternalEmployeeRequest req = new ProvisionFromExternalEmployeeRequest();
        req.setExternalEmployeeId("E_NOMAP");
        req.setSourceSystem("AD");
        req.setChangeReason("매핑 없음 테스트");

        provisioningService.provisionFromExternalEmployee(req, "admin", "127.0.0.1", "JUnit");

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT department_code FROM app_user WHERE name = '매핑없음'")) {
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getObject("department_code")).isNull();
            }
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }

    @Test
    @DisplayName("duplicate external key: EXTERNAL_IDENTITY_CONFLICT with existingUsername and existingAppUserId in details")
    void provisionConflictIncludesExistingUserDetails() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("INSERT INTO app_user (username, password_hash, role, is_system_admin) "
                    + "VALUES ('dup_user', 'x', 'USER', false)");
            stmt.execute("INSERT INTO app_user_external_identity (app_user_id, source_system, external_employee_id) "
                    + "VALUES (1, 'AD', 'E_ORG')");
        }

        ProvisionFromExternalEmployeeRequest req = new ProvisionFromExternalEmployeeRequest();
        req.setExternalEmployeeId("E_ORG");
        req.setSourceSystem("AD");
        req.setChangeReason("충돌 시나리오");

        CustomException ex = assertThrows(CustomException.class,
                () -> provisioningService.provisionFromExternalEmployee(req, "admin", "127.0.0.1", "JUnit"));
        assertThat(ex.getErrorCode()).isEqualTo("EXTERNAL_IDENTITY_CONFLICT");
        assertThat(ex.getDetails()).isNotNull();
        assertThat(ex.getDetails()).containsEntry("existingUsername", "dup_user");
        assertThat(ex.getDetails()).containsEntry("existingAppUserId", 1L);
    }

    @Test
    @DisplayName("TC-02: active user with same trimmed employee_number → USER_EMPLOYEE_NUMBER_DUPLICATED, no second user")
    void provisionFailsWhenAnotherActiveUserHasSameEmployeeNumber() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("INSERT INTO app_user (username, password_hash, role, is_system_admin, employee_number) "
                    + "VALUES ('existing_emp_dup', 'x', 'USER', false, '20260001')");
            stmt.execute("INSERT INTO ext_employee (source_system, external_employee_id, employee_number, "
                    + "display_name, job_title, external_department_id) "
                    + "VALUES ('AD', 'E_DUP_EMP', ' 20260001 ', '중복사번신규', 'STF', NULL)");
        }

        ProvisionFromExternalEmployeeRequest req = new ProvisionFromExternalEmployeeRequest();
        req.setExternalEmployeeId("E_DUP_EMP");
        req.setSourceSystem("AD");
        req.setDepartmentCode("DEPT_FROM_REQ");
        req.setChangeReason("사번 충돌 시나리오");

        CustomException ex = assertThrows(CustomException.class,
                () -> provisioningService.provisionFromExternalEmployee(req, "admin", "127.0.0.1", "JUnit"));
        assertThat(ex.getErrorCode()).isEqualTo("USER_EMPLOYEE_NUMBER_DUPLICATED");

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) FROM app_user WHERE employee_number = '20260001' AND deleted_at IS NULL")) {
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getLong(1)).isEqualTo(1L);
            }
        }
    }

    @Test
    @DisplayName("TC-05: only soft-deleted user has same employee_number → provisioning succeeds")
    void provisionSucceedsWhenOnlySoftDeletedUserHasSameEmployeeNumber() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("INSERT INTO app_user (username, password_hash, role, is_system_admin, employee_number, deleted_at) "
                    + "VALUES ('soft_deleted_emp', 'x', 'USER', false, '20265001', CURRENT_TIMESTAMP)");
            stmt.execute("INSERT INTO ext_employee (source_system, external_employee_id, employee_number, "
                    + "display_name, job_title, external_department_id) "
                    + "VALUES ('AD', 'E_AFTER_SOFT', '20265001', '소프트삭제후신규', 'STF', NULL)");
        }

        ProvisionFromExternalEmployeeRequest req = new ProvisionFromExternalEmployeeRequest();
        req.setExternalEmployeeId("E_AFTER_SOFT");
        req.setSourceSystem("AD");
        req.setDepartmentCode("DEPT_FROM_REQ");
        req.setChangeReason("소프트삭제 사번 재사용");

        provisioningService.provisionFromExternalEmployee(req, "admin", "127.0.0.1", "JUnit");

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT COUNT(*) FROM app_user WHERE employee_number = '20265001' AND deleted_at IS NULL")) {
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getLong(1)).isEqualTo(1L);
            }
        }
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "SELECT username FROM app_user WHERE name = '소프트삭제후신규' AND deleted_at IS NULL")) {
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("username")).isNotBlank();
            }
        }
    }

    @Test
    @DisplayName("missing changeReason → INVALID_INPUT")
    void provisionWithoutChangeReason_returnsInvalidInput() {
        ProvisionFromExternalEmployeeRequest req = new ProvisionFromExternalEmployeeRequest();
        req.setExternalEmployeeId("E_NOMAP");
        req.setSourceSystem("AD");

        CustomException ex = assertThrows(CustomException.class,
                () -> provisioningService.provisionFromExternalEmployee(req, "admin", "127.0.0.1", "JUnit"));
        assertThat(ex.getErrorCode()).isEqualTo("INVALID_INPUT");
    }
}
