package com.logmng.service;

import com.logmng.constants.ScreenConstants;
import com.logmng.dto.request.SearchHistoryCreateRequest;
import com.logmng.dto.request.SearchHistoryListRequest;
import com.logmng.dto.response.SearchHistoryListResponse;
import com.logmng.exception.CustomException;
import com.logmng.util.CryptoUtil;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.test.util.ReflectionTestUtils;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Unit tests for SearchHistoryService (decryption approval snapshot).
 * Uses H2 in-memory DB to avoid mocking DataSource (Java 17+ Mockito limitations with JDBC interfaces).
 * Ref: docs/requirements/20260224-decryption-snapshot-final-design-en.md §6.1, §6.4
 */
@ExtendWith(MockitoExtension.class)
class SearchHistoryServiceTest {

    private static final String H2_URL = "jdbc:h2:mem:search_history_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH";
    /** Payload inside "[...]" that is long enough (≥32 chars) to be treated as encrypted by hasEncryptedData. */
    private static final String LONG_ENC_PAYLOAD = "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5";

    private DataSource dataSource;
    private StubLogDbService stubLogDbService;
    private DecryptApproverService decryptApproverService;
    private SearchHistoryService searchHistoryService;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = createH2DataSource();
        clearAllTables(dataSource);
        CryptoUtil cryptoUtil = new CryptoUtil();
        ReflectionTestUtils.setField(cryptoUtil, "encryptionKey", "test-key-32-bytes-long!!!!!!!!!");
        ReflectionTestUtils.setField(cryptoUtil, "decryptionEnabled", true);
        stubLogDbService = new StubLogDbService(dataSource, dataSource, cryptoUtil);
        decryptApproverService = new StubDecryptApproverService();
        searchHistoryService = new SearchHistoryService(dataSource, stubLogDbService, decryptApproverService);
    }

    private static DataSource createH2DataSource() throws Exception {
        Class.forName("org.h2.Driver");
        try (Connection conn = java.sql.DriverManager.getConnection(H2_URL);
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS search_history_approved_row (" +
                    "search_history_id BIGINT NOT NULL, log_type VARCHAR(50) NOT NULL, row_id VARCHAR(512) NOT NULL, " +
                    "row_status VARCHAR(256) NOT NULL DEFAULT '', " +
                    "PRIMARY KEY (search_history_id, log_type, row_id, row_status))");
            stmt.execute("CREATE TABLE IF NOT EXISTS search_history (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT, log_type VARCHAR(50), search_params CLOB, request_reason CLOB, " +
                    "requested_at TIMESTAMP, expires_at TIMESTAMP, approval_status VARCHAR(20), approved_by_user_id BIGINT, approved_by VARCHAR(100), approved_at TIMESTAMP, " +
                    "rejected_by VARCHAR(100), rejected_at TIMESTAMP, rejection_reason VARCHAR(500), created_at TIMESTAMP, updated_at TIMESTAMP, " +
                    "search_result_total_count INT, decryption_target_count INT)");
            stmt.execute("CREATE TABLE IF NOT EXISTS department (code VARCHAR(50) PRIMARY KEY, name VARCHAR(200))");
            stmt.execute("CREATE TABLE IF NOT EXISTS app_user (" +
                    "id BIGINT, username VARCHAR(100) PRIMARY KEY, department_code VARCHAR(50), name VARCHAR(200))");
            stmt.execute("CREATE TABLE IF NOT EXISTS user_decryption_allowed (" +
                    "user_id BIGINT NOT NULL, screen VARCHAR(50) NOT NULL, guid VARCHAR(512) NOT NULL, " +
                    "row_status VARCHAR(256) NOT NULL DEFAULT '', valid_until TIMESTAMP NOT NULL, " +
                    "PRIMARY KEY (user_id, screen, guid, row_status))");
        }
        org.h2.jdbcx.JdbcDataSource ds = new org.h2.jdbcx.JdbcDataSource();
        ds.setURL(H2_URL);
        return ds;
    }

    // ---- isRowInApprovedSnapshot ----

    @Test
    void isRowInApprovedSnapshot_returnsFalseWhenSearchHistoryIdIsNull() {
        assertThat(searchHistoryService.isRowInApprovedSnapshot(null, "java_fw_imglog", "guid-1")).isFalse();
    }

    @Test
    void isRowInApprovedSnapshot_returnsFalseWhenLogTypeIsNull() {
        assertThat(searchHistoryService.isRowInApprovedSnapshot(1L, null, "guid-1")).isFalse();
    }

    @Test
    void isRowInApprovedSnapshot_returnsFalseWhenLogTypeIsBlank() {
        assertThat(searchHistoryService.isRowInApprovedSnapshot(1L, "   ", "guid-1")).isFalse();
    }

    @Test
    void isRowInApprovedSnapshot_returnsFalseWhenRowIdIsNull() {
        assertThat(searchHistoryService.isRowInApprovedSnapshot(1L, "java_fw_imglog", null)).isFalse();
    }

    @Test
    void isRowInApprovedSnapshot_returnsFalseWhenRowIdIsBlank() {
        assertThat(searchHistoryService.isRowInApprovedSnapshot(1L, "java_fw_imglog", "  ")).isFalse();
    }

    @Test
    void isRowInApprovedSnapshot_returnsTrueWhenRowExists() throws Exception {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO search_history_approved_row (search_history_id, log_type, row_id, row_status) VALUES (?, ?, ?, '')")) {
            ps.setLong(1, 1L);
            ps.setString(2, "java_fw_imglog");
            ps.setString(3, "guid-123");
            ps.executeUpdate();
        }

        boolean result = searchHistoryService.isRowInApprovedSnapshot(1L, "java_fw_imglog", "guid-123", "");

        assertThat(result).isTrue();
    }

    @Test
    void isRowInApprovedSnapshot_returnsFalseWhenRowDoesNotExist() {
        boolean result = searchHistoryService.isRowInApprovedSnapshot(2L, "java_fw_imglog", "unknown-guid");

        assertThat(result).isFalse();
    }

    @Test
    void isRowInApprovedSnapshot_returnsFalseWhenWrongLogType() throws Exception {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO search_history_approved_row (search_history_id, log_type, row_id, row_status) VALUES (?, ?, ?, '')")) {
            ps.setLong(1, 3L);
            ps.setString(2, "java_fw_imglog");
            ps.setString(3, "guid-x");
            ps.executeUpdate();
        }

        boolean result = searchHistoryService.isRowInApprovedSnapshot(3L, "pb_feplog", "guid-x");

        assertThat(result).isFalse();
    }

    // ---- approve: snapshot insert (mocked LogDbService, H2 for persistence) ----

    @Test
    void approve_insertsSnapshotRowsAndSetsApproved() throws Exception {
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        insertAppUser(dataSource, 20260002L, "approver1", "D01");
        createSearchHistoryTableAndInsertPending(dataSource, 10L, 20260001L, "java_fw_imglog", "{}");

        // Rows must have encrypted-style content (≥32 chars inside brackets) in datastring/headerstring (req 20260318)
        List<Map<String, Object>> searchData = List.of(
                Map.of("guid", "guid-a", "datastring", "{\"x\":\"[" + LONG_ENC_PAYLOAD + "]\"}"),
                Map.of("guid", "guid-b", "headerstring", "{\"x\":\"[" + LONG_ENC_PAYLOAD + "]\"}")
        );
        stubLogDbService.setSearchLogsData(searchData);

        Map<String, Object> result = searchHistoryService.approve(10L, 20260002L);

        assertThat(result).isNotNull();
        assertThat(result.get("approvalStatus")).isEqualTo("APPROVED");
        assertThat(result.get("id")).isEqualTo(10L);

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT row_id FROM search_history_approved_row WHERE search_history_id = ? AND log_type = ? ORDER BY row_id")) {
            ps.setLong(1, 10L);
            ps.setString(2, "java_fw_imglog");
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("row_id")).isEqualTo("guid-a");
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("row_id")).isEqualTo("guid-b");
                assertThat(rs.next()).isFalse();
            }
        }
    }

    @Test
    void approve_withEmptySearchResults_stillSetsApproved() throws Exception {
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        insertAppUser(dataSource, 20260003L, "approver2", "D01");
        createSearchHistoryTableAndInsertPending(dataSource, 20L, 20260001L, "java_fw_imglog", "{}");

        stubLogDbService.setSearchLogsData(Collections.emptyList());

        Map<String, Object> result = searchHistoryService.approve(20L, 20260003L);

        assertThat(result).isNotNull();
        assertThat(result.get("approvalStatus")).isEqualTo("APPROVED");
    }

    /** TC-02: user1 approves user2's request; user1 not allowed → 403, not 500 */
    @Test
    void approve_whenCanApproveForRequesterReturnsFalse_throws403() throws Exception {
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        insertAppUser(dataSource, 20260002L, "approver1", "D02");
        createSearchHistoryTableAndInsertPending(dataSource, 11L, 20260001L, "java_fw_imglog", "{}");
        DecryptApproverService noApprovalService = new DecryptApproverService(dataSource, new DepartmentService(dataSource)) {
            @Override
            public boolean canApproveForRequester(Long approverUserId, Long requesterUserId) {
                return false;
            }
        };
        SearchHistoryService svc = new SearchHistoryService(dataSource, stubLogDbService, noApprovalService);

        assertThatThrownBy(() -> svc.approve(11L, 20260002L))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getHttpStatus()).isEqualTo(HttpStatus.FORBIDDEN);
                    assertThat(ex.getErrorCode()).isEqualTo("FUNCTION_NOT_ALLOWED");
                });
    }

    /** Unknown approver id (not in decrypt_approver) → 403. Req 20260316: id-based; no permission → 403. */
    @Test
    void approve_whenApproverNotAllowed_throws403() throws Exception {
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        createSearchHistoryTableAndInsertPending(dataSource, 12L, 20260001L, "java_fw_imglog", "{}");
        long unknownApproverId = 999999L;
        DecryptApproverService noApprovalStub = new DecryptApproverService(dataSource, new DepartmentService(dataSource)) {
            @Override
            public boolean canApproveForRequester(Long approverUserId, Long requesterUserId) {
                return approverUserId != null && approverUserId != 999999L;
            }
        };
        SearchHistoryService svc = new SearchHistoryService(dataSource, stubLogDbService, noApprovalStub);

        assertThatThrownBy(() -> svc.approve(12L, unknownApproverId))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getHttpStatus()).isEqualTo(HttpStatus.FORBIDDEN);
                    assertThat(ex.getErrorCode()).isEqualTo("FUNCTION_NOT_ALLOWED");
                });
    }

    /** Malformed search_params JSON → 400, not 500 */
    @Test
    void approve_whenMalformedSearchParams_throws400() throws Exception {
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        insertAppUser(dataSource, 20260002L, "approver1", "D01");
        createSearchHistoryTableAndInsertPending(dataSource, 13L, 20260001L, "java_fw_imglog", "{ invalid json }");
        stubLogDbService.setSearchLogsData(Collections.emptyList());

        assertThatThrownBy(() -> searchHistoryService.approve(13L, 20260002L))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getHttpStatus()).isEqualTo(HttpStatus.BAD_REQUEST);
                    assertThat(ex.getErrorCode()).isEqualTo("INVALID_SEARCH_PARAMS");
                });
    }

    /** search_params containing UI-only field showDecryptOption deserialize and approve successfully (no 500) */
    @Test
    void approve_whenSearchParamsContainShowDecryptOption_succeeds() throws Exception {
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        insertAppUser(dataSource, 20260002L, "approver1", "D01");
        String searchParamsWithUiField = "{\"logType\":\"java_fw_imglog\",\"showDecryptOption\":true}";
        createSearchHistoryTableAndInsertPending(dataSource, 14L, 20260001L, "java_fw_imglog", searchParamsWithUiField);
        stubLogDbService.setSearchLogsData(List.of(Map.of("guid", "guid-x", "datastring", "{\"p\":\"[" + LONG_ENC_PAYLOAD + "]\"}")));

        Map<String, Object> result = searchHistoryService.approve(14L, 20260002L);

        assertThat(result).isNotNull();
        assertThat(result.get("approvalStatus")).isEqualTo("APPROVED");
        assertThat(result.get("id")).isEqualTo(14L);
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT row_id FROM search_history_approved_row WHERE search_history_id = ? AND log_type = ?")) {
            ps.setLong(1, 14L);
            ps.setString(2, "java_fw_imglog");
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("row_id")).isEqualTo("guid-x");
            }
        }
    }

    // ---- Req 20260318: only encrypted row IDs in snapshot and decryption-allowed (TC-01 to TC-05) ----

    /** TC-01: approve with only encrypted rows → all in search_history_approved_row and in decryption-allowed. */
    @Test
    void approve_withOnlyEncryptedRows_includesAllInSnapshotAndAllowed() throws Exception {
        RecordingDecryptionAllowedService recordingAllowed = new RecordingDecryptionAllowedService(dataSource);
        SearchHistoryService svc = new SearchHistoryService(dataSource, stubLogDbService, decryptApproverService, null, recordingAllowed, false);
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        insertAppUser(dataSource, 20260002L, "approver1", "D01");
        createSearchHistoryTableAndInsertPending(dataSource, 30L, 20260001L, "java_fw_imglog", "{}");

        List<Map<String, Object>> searchData = List.of(
                Map.of("guid", "enc-1", "datastring", "{\"p\":\"[" + LONG_ENC_PAYLOAD + "]\"}"),
                Map.of("guid", "enc-2", "headerstring", "{\"p\":\"[" + LONG_ENC_PAYLOAD + "]\"}")
        );
        stubLogDbService.setSearchLogsData(searchData);

        Map<String, Object> result = svc.approve(30L, 20260002L);

        assertThat(result.get("approvalStatus")).isEqualTo("APPROVED");
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT row_id FROM search_history_approved_row WHERE search_history_id = ? AND log_type = ? ORDER BY row_id")) {
            ps.setLong(1, 30L);
            ps.setString(2, "java_fw_imglog");
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("row_id")).isEqualTo("enc-1");
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("row_id")).isEqualTo("enc-2");
                assertThat(rs.next()).isFalse();
            }
        }
        assertThat(recordingAllowed.getLastKeys()).extracting(com.logmng.dto.DecryptionRowKey::getGuid).containsExactlyInAnyOrder("enc-1", "enc-2");
    }

    /** TC-02: approve with only plain rows → none in search_history_approved_row and none in decryption-allowed. */
    @Test
    void approve_withOnlyPlainRows_includesNoneInSnapshotOrAllowed() throws Exception {
        RecordingDecryptionAllowedService recordingAllowed = new RecordingDecryptionAllowedService(dataSource);
        SearchHistoryService svc = new SearchHistoryService(dataSource, stubLogDbService, decryptApproverService, null, recordingAllowed, false);
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        insertAppUser(dataSource, 20260002L, "approver1", "D01");
        createSearchHistoryTableAndInsertPending(dataSource, 31L, 20260001L, "java_fw_imglog", "{}");

        List<Map<String, Object>> searchData = List.of(
                Map.of("guid", "plain-1"),
                Map.of("guid", "plain-2", "datastring", "{\"id\":\"plain\"}", "headerstring", "plain")
        );
        stubLogDbService.setSearchLogsData(searchData);

        Map<String, Object> result = svc.approve(31L, 20260002L);

        assertThat(result.get("approvalStatus")).isEqualTo("APPROVED");
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT row_id FROM search_history_approved_row WHERE search_history_id = ? AND log_type = ?")) {
            ps.setLong(1, 31L);
            ps.setString(2, "java_fw_imglog");
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isFalse();
            }
        }
        assertThat(recordingAllowed.getLastKeys()).isEmpty();
    }

    /** TC-03: approve with mixed plain and encrypted rows → only encrypted row IDs in snapshot and allowed. */
    @Test
    void approve_withMixedPlainAndEncrypted_includesOnlyEncryptedInSnapshotAndAllowed() throws Exception {
        RecordingDecryptionAllowedService recordingAllowed = new RecordingDecryptionAllowedService(dataSource);
        SearchHistoryService svc = new SearchHistoryService(dataSource, stubLogDbService, decryptApproverService, null, recordingAllowed, false);
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        insertAppUser(dataSource, 20260002L, "approver1", "D01");
        createSearchHistoryTableAndInsertPending(dataSource, 32L, 20260001L, "java_fw_imglog", "{}");

        List<Map<String, Object>> searchData = List.of(
                Map.of("guid", "plain-a"),
                Map.of("guid", "enc-b", "datastring", "{\"p\":\"[" + LONG_ENC_PAYLOAD + "]\"}"),
                Map.of("guid", "plain-c", "datastring", "no bracket"),
                Map.of("guid", "enc-d", "headerstring", "{\"p\":\"[" + LONG_ENC_PAYLOAD + "]\"}")
        );
        stubLogDbService.setSearchLogsData(searchData);

        Map<String, Object> result = svc.approve(32L, 20260002L);

        assertThat(result.get("approvalStatus")).isEqualTo("APPROVED");
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT row_id FROM search_history_approved_row WHERE search_history_id = ? AND log_type = ? ORDER BY row_id")) {
            ps.setLong(1, 32L);
            ps.setString(2, "java_fw_imglog");
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("row_id")).isEqualTo("enc-b");
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("row_id")).isEqualTo("enc-d");
                assertThat(rs.next()).isFalse();
            }
        }
        assertThat(recordingAllowed.getLastKeys()).extracting(com.logmng.dto.DecryptionRowKey::getGuid).containsExactlyInAnyOrder("enc-b", "enc-d");
    }

    /** TC-04: row with datastring null, headerstring containing encrypted-style quoted "[...]" → included. */
    @Test
    void approve_rowWithDatastringNullAndHeaderstringEncryptedStyle_includedInSnapshot() throws Exception {
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        insertAppUser(dataSource, 20260002L, "approver1", "D01");
        createSearchHistoryTableAndInsertPending(dataSource, 33L, 20260001L, "java_fw_imglog", "{}");

        List<Map<String, Object>> searchData = List.of(
                Map.of("guid", "guid-tc04", "headerstring", "{\"h\":\"[" + LONG_ENC_PAYLOAD + "]\"}")
        );
        stubLogDbService.setSearchLogsData(searchData);

        searchHistoryService.approve(33L, 20260002L);

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT row_id FROM search_history_approved_row WHERE search_history_id = ? AND log_type = ?")) {
            ps.setLong(1, 33L);
            ps.setString(2, "java_fw_imglog");
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("row_id")).isEqualTo("guid-tc04");
            }
        }
    }

    /** TC-05: row with empty datastring and headerstring, no data/header → not included. */
    @Test
    void approve_rowWithEmptyDatastringHeaderstringNoDataHeader_notIncludedInSnapshot() throws Exception {
        insertAppUser(dataSource, 20260001L, "requester1", "D01");
        insertAppUser(dataSource, 20260002L, "approver1", "D01");
        createSearchHistoryTableAndInsertPending(dataSource, 34L, 20260001L, "java_fw_imglog", "{}");

        List<Map<String, Object>> searchData = List.of(
                Map.of("guid", "guid-tc05", "datastring", "", "headerstring", "")
        );
        stubLogDbService.setSearchLogsData(searchData);

        searchHistoryService.approve(34L, 20260002L);

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT row_id FROM search_history_approved_row WHERE search_history_id = ? AND log_type = ?")) {
            ps.setLong(1, 34L);
            ps.setString(2, "java_fw_imglog");
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isFalse();
            }
        }
    }

    /** hasEncryptedData: headerstring contains encrypted-style quoted "[...]" with long payload (≥32 chars) → true. */
    @Test
    void hasEncryptedData_javaFwImglog_headerstringContainsQuotedBracketValue_returnsTrue() {
        String longPayload = "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5"; // 32 chars
        Map<String, Object> row = Map.of("guid", "x", "headerstring", "{\"h\":\"[" + longPayload + "]\"}");
        assertThat(SearchHistoryService.hasEncryptedData("java_fw_imglog", row)).isTrue();
    }

    /** hasEncryptedData: empty datastring and headerstring → false. */
    @Test
    void hasEncryptedData_javaFwImglog_emptyDatastringHeaderstringNoDataHeader_returnsFalse() {
        Map<String, Object> row = Map.of("guid", "x", "datastring", "", "headerstring", "");
        assertThat(SearchHistoryService.hasEncryptedData("java_fw_imglog", row)).isFalse();
    }

    /** hasEncryptedData: plain datastring and non-empty data (no encrypted-style in datastring/headerstring) → false. */
    @Test
    void hasEncryptedData_javaFwImglog_plainDatastringWithNonEmptyData_returnsFalse() {
        Map<String, Object> row = Map.of("guid", "x", "datastring", "{\"id\":\"plain\",\"name\":\"\"}", "data", " encrypted ");
        assertThat(SearchHistoryService.hasEncryptedData("java_fw_imglog", row)).isFalse();
    }

    /** hasEncryptedData: datastring contains quoted bracket-wrapped value with long payload (≥32 chars) → true. */
    @Test
    void hasEncryptedData_javaFwImglog_datastringContainsQuotedBracketValue_returnsTrue() {
        String longPayload = "0123456789abcdef0123456789abcdef"; // 32 chars (encrypted-style)
        Map<String, Object> row = Map.of("guid", "x", "datastring", "{\"p\":\"[" + longPayload + "]\"}");
        assertThat(SearchHistoryService.hasEncryptedData("java_fw_imglog", row)).isTrue();
    }

    /** hasEncryptedData: plain datastring with short quoted bracket value (e.g. "size":"[100,200]") → false. */
    @Test
    void hasEncryptedData_javaFwImglog_plainJsonWithShortBracketValue_returnsFalse() {
        Map<String, Object> row = Map.of("guid", "x", "datastring", "{\"id\":\"x\",\"size\":\"[100,200]\"}");
        assertThat(SearchHistoryService.hasEncryptedData("java_fw_imglog", row)).isFalse();
    }

    /** hasEncryptedData: datastring with short "[1,2,3]" style (dims) → false. */
    @Test
    void hasEncryptedData_javaFwImglog_plainJsonWithShortDimsBracket_returnsFalse() {
        Map<String, Object> row = Map.of("guid", "y", "datastring", "{\"dims\":\"[1,2,3]\"}");
        assertThat(SearchHistoryService.hasEncryptedData("java_fw_imglog", row)).isFalse();
    }

    /** hasEncryptedData: pb_feplog → false (no encrypted data for approval). */
    @Test
    void hasEncryptedData_pbFeplog_returnsFalse() {
        Map<String, Object> row = Map.of("log_type", "pb_feplog", "id", 1, "datastring", "[x]");
        assertThat(SearchHistoryService.hasEncryptedData("pb_feplog", row)).isFalse();
    }

    private static void createSearchHistoryTableAndInsertPending(DataSource ds, long id, long requesterUserId, String logType, String searchParams) throws Exception {
        createSearchHistoryTableAndInsertPending(ds, id, requesterUserId, logType, searchParams, null);
    }

    private static void createSearchHistoryTableAndInsertPending(DataSource ds, long id, long requesterUserId, String logType, String searchParams, String requestReason) throws Exception {
        Timestamp requestedAt = Timestamp.from(Instant.now());
        Timestamp expiresAt = Timestamp.from(Instant.now().plusSeconds(86400));
        try (Connection conn = ds.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO search_history (id, user_id, log_type, search_params, request_reason, approval_status, requested_at, expires_at, updated_at) VALUES (?, ?, ?, ?, ?, 'PENDING', ?, ?, CURRENT_TIMESTAMP)")) {
            ps.setLong(1, id);
            ps.setObject(2, requesterUserId);
            ps.setString(3, logType);
            ps.setString(4, searchParams);
            ps.setString(5, requestReason);
            ps.setTimestamp(6, requestedAt);
            ps.setTimestamp(7, expiresAt);
            ps.executeUpdate();
        }
    }

    /** Insert a search_history row. ownerUserId = numeric app_user.id (req 20260316). */
    private static long insertSearchHistoryRow(DataSource ds, long id, long ownerUserId, boolean expired) throws Exception {
        return insertSearchHistoryRow(ds, id, ownerUserId, expired, Instant.now().minusSeconds(3600));
    }

    private static long insertSearchHistoryRow(DataSource ds, long id, long ownerUserId, boolean expired, Instant requestedAtInstant) throws Exception {
        String status = expired ? "EXPIRED" : "PENDING";
        return insertSearchHistoryRow(ds, id, ownerUserId, expired, requestedAtInstant, null, status);
    }

    private static long insertSearchHistoryRow(DataSource ds, long id, long ownerUserId, boolean expired, Instant requestedAtInstant, String requestReason, String approvalStatus) throws Exception {
        return insertSearchHistoryRow(ds, id, ownerUserId, expired, requestedAtInstant, requestReason, approvalStatus, null);
    }

    /** searchParamsJson: JSON for search_params column (default "{}"); used for getDetail re-run search tests. */
    private static long insertSearchHistoryRow(DataSource ds, long id, long ownerUserId, boolean expired, Instant requestedAtInstant, String requestReason, String approvalStatus, String searchParamsJson) throws Exception {
        Timestamp expiresAt = expired ? Timestamp.from(Instant.now().minusSeconds(3600)) : Timestamp.from(Instant.now().plusSeconds(86400));
        String status = approvalStatus != null ? approvalStatus : (expired ? "EXPIRED" : "PENDING");
        String sp = searchParamsJson != null ? searchParamsJson : "{}";
        try (Connection conn = ds.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO search_history (id, user_id, log_type, search_params, request_reason, requested_at, expires_at, approval_status, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)")) {
            ps.setLong(1, id);
            ps.setObject(2, ownerUserId);
            ps.setString(3, "java_fw_imglog");
            ps.setString(4, sp);
            ps.setString(5, requestReason);
            ps.setTimestamp(6, Timestamp.from(requestedAtInstant));
            ps.setTimestamp(7, expiresAt);
            ps.setString(8, status);
            ps.executeUpdate();
        }
        return id;
    }

    private static void insertAppUser(DataSource ds, long id, String username, String departmentCode) throws Exception {
        try (Connection conn = ds.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO app_user (id, username, department_code) VALUES (?, ?, ?)")) {
            ps.setLong(1, id);
            ps.setString(2, username);
            ps.setString(3, departmentCode);
            ps.executeUpdate();
        }
    }

    private static SearchHistoryListRequest newListRequest(Long actorUserId) {
        SearchHistoryListRequest request = new SearchHistoryListRequest();
        request.setActorUserId(actorUserId);
        request.setPage(1);
        request.setPageSize(20);
        request.setSortField("requested_at");
        request.setSortDirection("desc");
        return request;
    }

    // ---- Search-history requester filter + paging (req 20260313) ----

    @Test
    void list_scopeAll_filtersByUserId_andCountMatchesRows() throws Exception {
        insertAppUser(dataSource, 20260001L, "alpha-user", "D01");
        insertAppUser(dataSource, 20260002L, "beta-user", "D02");
        insertSearchHistoryRow(dataSource, 100L, 20260001L, false);
        insertSearchHistoryRow(dataSource, 101L, 20260001L, false);
        insertSearchHistoryRow(dataSource, 102L, 20260002L, false);

        SearchHistoryListRequest request = newListRequest(20269999L);
        request.setUserId(20260001L);
        SearchHistoryListResponse resp = searchHistoryService.list(request);

        assertThat(resp.getData()).hasSize(2);
        assertThat(resp.getData()).allMatch(row -> Long.valueOf(20260001L).equals(row.get("userId")));
        assertThat(resp.getPagination().getTotalCount()).isEqualTo(2);
        assertThat(resp.getPagination().getTotalPages()).isEqualTo(1);
    }

    @Test
    void list_scopeAll_filtersByUsernamePartial_andCountMatchesRows() throws Exception {
        insertAppUser(dataSource, 20260001L, "alice-admin", "D01");
        insertAppUser(dataSource, 20260002L, "alice-viewer", "D02");
        insertAppUser(dataSource, 20260003L, "bob-user", "D01");
        insertSearchHistoryRow(dataSource, 110L, 20260001L, false);
        insertSearchHistoryRow(dataSource, 111L, 20260002L, false);
        insertSearchHistoryRow(dataSource, 112L, 20260003L, false);

        SearchHistoryListRequest request = newListRequest(20269999L);
        request.setUsername("alice");
        SearchHistoryListResponse resp = searchHistoryService.list(request);

        assertThat(resp.getData()).hasSize(2);
        assertThat(resp.getData()).extracting(row -> row.get("userId"))
                .containsExactlyInAnyOrder(20260001L, 20260002L);
        assertThat(resp.getPagination().getTotalCount()).isEqualTo(2);
    }

    @Test
    void list_scopeAll_filtersByDepartmentExact() throws Exception {
        insertAppUser(dataSource, 20260001L, "sales-user", "SALES");
        insertAppUser(dataSource, 20260002L, "research-user", "RESEARCH");
        insertSearchHistoryRow(dataSource, 120L, 20260001L, false);
        insertSearchHistoryRow(dataSource, 121L, 20260002L, false);

        SearchHistoryListRequest request = newListRequest(20269999L);
        request.setDepartment("SALES");
        SearchHistoryListResponse resp = searchHistoryService.list(request);

        assertThat(resp.getData()).hasSize(1);
        assertThat(resp.getData().get(0).get("userId")).isEqualTo(20260001L);
        assertThat(resp.getPagination().getTotalCount()).isEqualTo(1);
    }

    @Test
    void list_scopeTeam_appliesAllowedUserIds_beforeRequesterFilters() throws Exception {
        insertAppUser(dataSource, 20260001L, "current-user", "D01");
        insertAppUser(dataSource, 20260002L, "team-mate", "D01");
        insertAppUser(dataSource, 20260003L, "outside-user", "D02");
        insertSearchHistoryRow(dataSource, 130L, 20260001L, false);
        insertSearchHistoryRow(dataSource, 131L, 20260002L, false);
        insertSearchHistoryRow(dataSource, 132L, 20260003L, false);

        SearchHistoryListRequest request = newListRequest(20260001L);
        request.setAllowedUserIds(List.of(20260001L, 20260002L));
        request.setUserId(20260003L);
        SearchHistoryListResponse outsideResp = searchHistoryService.list(request);

        assertThat(outsideResp.getData()).isEmpty();
        assertThat(outsideResp.getPagination().getTotalCount()).isEqualTo(0);

        request.setUserId(null);
        request.setUsername("team");
        SearchHistoryListResponse teamResp = searchHistoryService.list(request);

        assertThat(teamResp.getData()).hasSize(1);
        assertThat(teamResp.getData().get(0).get("userId")).isEqualTo(20260002L);
        assertThat(teamResp.getPagination().getTotalCount()).isEqualTo(1);
    }

    @Test
    void list_usesConsistentFilterSetForCountAndPageRows_andKeepsDefaultSortDesc() throws Exception {
        insertAppUser(dataSource, 20260001L, "alpha-user", "D01");
        insertSearchHistoryRow(dataSource, 140L, 20260001L, false, Instant.parse("2026-03-13T01:00:00Z"));
        insertSearchHistoryRow(dataSource, 141L, 20260001L, false, Instant.parse("2026-03-13T02:00:00Z"));
        insertSearchHistoryRow(dataSource, 142L, 20260001L, false, Instant.parse("2026-03-13T03:00:00Z"));

        SearchHistoryListRequest request = newListRequest(20269999L);
        request.setUserId(20260001L);
        request.setPageSize(2);
        SearchHistoryListResponse resp = searchHistoryService.list(request);

        assertThat(resp.getPagination().getTotalCount()).isEqualTo(3);
        assertThat(resp.getPagination().getTotalPages()).isEqualTo(2);
        assertThat(resp.getData()).hasSize(2);
        assertThat(resp.getData().get(0).get("id")).isEqualTo(142L);
        assertThat(resp.getData().get(1).get("id")).isEqualTo(141L);
    }

    /** When app_user LEFT JOIN does not match (orphan user_id), requester columns filled from resolve by user_id or fallback. Req 20260316 TC-07/TC-15. */
    @Test
    void list_whenAppUserJoinDoesNotMatch_populatesRequesterFromFallbackOrUserId() throws Exception {
        insertAppUser(dataSource, 20260001L, "known-user", "D01");
        insertSearchHistoryRow(dataSource, 150L, 20260001L, false);
        long orphanId = 999999L;
        insertSearchHistoryRow(dataSource, 151L, orphanId, false);

        SearchHistoryListRequest request = newListRequest(20269999L);
        request.setAllowedUserIds(List.of(20260001L, orphanId));
        SearchHistoryListResponse resp = searchHistoryService.list(request);

        assertThat(resp.getData()).hasSize(2);
        Map<String, Object> rowWithJoin = resp.getData().stream().filter(r -> 150L == ((Number) r.get("id")).longValue()).findFirst().orElseThrow();
        Map<String, Object> rowNoJoin = resp.getData().stream().filter(r -> 151L == ((Number) r.get("id")).longValue()).findFirst().orElseThrow();

        assertThat(rowWithJoin.get("requesterUsername")).isEqualTo("known-user");
        assertThat(rowWithJoin.get("requesterDisplayName")).isNotNull();

        assertThat(rowNoJoin.get("userId")).isEqualTo(orphanId);
        assertThat(rowNoJoin.get("requesterUsername")).isEqualTo(String.valueOf(orphanId));
        assertThat(rowNoJoin.get("requesterDisplayName")).isEqualTo(String.valueOf(orphanId));
    }

    @Test
    void create_computesAndStoresSearchResultTotalCountAndDecryptionTargetCount() throws Exception {
        insertAppUser(dataSource, 20260001L, "u1", "D01");
        stubLogDbService.setCreateSnapshotBehavior(100L, List.of(
                Map.of("guid", "a", "datastring", "{\"p\":\"[" + LONG_ENC_PAYLOAD + "]\"}"),
                Map.of("guid", "b"),
                Map.of("guid", "c", "headerstring", "{\"h\":\"[" + LONG_ENC_PAYLOAD + "]\"}")));
        SearchHistoryCreateRequest req = new SearchHistoryCreateRequest();
        req.setLogType("java_fw_imglog");
        req.setSearchParams(Map.of("startDate", "2026-01-01"));
        Map<String, Object> out = searchHistoryService.create(20260001L, req);
        assertThat(out.get("searchResultTotalCount")).isEqualTo(100);
        assertThat(out.get("decryptionTargetCount")).isEqualTo(2);
        long id = ((Number) out.get("id")).longValue();
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT search_result_total_count, decryption_target_count FROM search_history WHERE id = ?")) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getInt(1)).isEqualTo(100);
                assertThat(rs.getInt(2)).isEqualTo(2);
            }
        }
    }

    /** TC-01 (req 20260318): Create without client counts; server computes; totalCount=48, 37 rows hasEncryptedData in window → DB and list/detail return 48 and 37. */
    @Test
    void create_withServerCompute_total48_decryption37_storesAndReturnsDistinctCounts() throws Exception {
        insertAppUser(dataSource, 20260001L, "u1", "D01");
        List<Map<String, Object>> rows = new java.util.ArrayList<>();
        for (int i = 0; i < 37; i++) {
            rows.add(Map.of("guid", "g-" + i, "datastring", "{\"p\":\"[" + LONG_ENC_PAYLOAD + "]\"}"));
        }
        for (int i = 37; i < 48; i++) {
            rows.add(Map.of("guid", "g-" + i, "datastring", "plain"));
        }
        stubLogDbService.setCreateSnapshotBehavior(48L, rows);
        SearchHistoryCreateRequest req = new SearchHistoryCreateRequest();
        req.setLogType("java_fw_imglog");
        req.setSearchParams(Map.of());
        Map<String, Object> out = searchHistoryService.create(20260001L, req);
        assertThat(out.get("searchResultTotalCount")).isEqualTo(48);
        assertThat(out.get("decryptionTargetCount")).isEqualTo(37);
        long id = ((Number) out.get("id")).longValue();
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT search_result_total_count, decryption_target_count FROM search_history WHERE id = ?")) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getInt(1)).isEqualTo(48);
                assertThat(rs.getInt(2)).isEqualTo(37);
            }
        }
        SearchHistoryListRequest listReq = newListRequest(20269999L);
        listReq.setUserId(20260001L);
        SearchHistoryListResponse listResp = searchHistoryService.list(listReq);
        assertThat(listResp.getData()).isNotEmpty();
        Map<String, Object> listRow = listResp.getData().stream().filter(r -> id == ((Number) r.get("id")).longValue()).findFirst().orElseThrow();
        assertThat(listRow.get("searchResultTotalCount")).isEqualTo(48);
        assertThat(listRow.get("decryptionTargetCount")).isEqualTo(37);
        Map<String, Object> detail = searchHistoryService.getDetail(20260001L, id);
        assertThat(detail.get("searchResultTotalCount")).isEqualTo(48);
        assertThat(detail.get("decryptionTargetCount")).isEqualTo(37);
    }

    @Test
    void create_whenTotalCountZero_storesZeroZeroWithoutSecondPageRows() throws Exception {
        insertAppUser(dataSource, 20260001L, "u2", "D01");
        stubLogDbService.setCreateSnapshotBehavior(0L, List.of(Map.of("guid", "should-not-use")));
        SearchHistoryCreateRequest req = new SearchHistoryCreateRequest();
        req.setLogType("java_fw_imglog");
        req.setSearchParams(Map.of());
        Map<String, Object> out = searchHistoryService.create(20260001L, req);
        assertThat(out.get("searchResultTotalCount")).isEqualTo(0);
        assertThat(out.get("decryptionTargetCount")).isEqualTo(0);
    }

    @Test
    void create_withClientOverride_skipsLogSearch() throws Exception {
        insertAppUser(dataSource, 20260001L, "u3", "D01");
        stubLogDbService.setCreateSnapshotBehavior(999L, List.of(Map.of("guid", "x", "datastring", "[a]")));
        SearchHistoryCreateRequest req = new SearchHistoryCreateRequest();
        req.setLogType("java_fw_imglog");
        req.setSearchParams(Map.of());
        req.setSearchResultTotalCount(7);
        req.setDecryptionTargetCount(3);
        Map<String, Object> out = searchHistoryService.create(20260001L, req);
        assertThat(out.get("searchResultTotalCount")).isEqualTo(7);
        assertThat(out.get("decryptionTargetCount")).isEqualTo(3);
    }

    @Test
    void create_whenOnlyOneCountOverride_throwsIllegalArgumentException() throws Exception {
        insertAppUser(dataSource, 20260001L, "u4", "D01");
        SearchHistoryCreateRequest req = new SearchHistoryCreateRequest();
        req.setLogType("java_fw_imglog");
        req.setSearchParams(Map.of());
        req.setSearchResultTotalCount(5);
        assertThatThrownBy(() -> searchHistoryService.create(20260001L, req))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("both");
    }

    @Test
    void list_includesSearchResultTotalCountAndDecryptionTargetCount() throws Exception {
        insertAppUser(dataSource, 20260001L, "alpha", "D01");
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO search_history (id, user_id, log_type, search_params, request_reason, requested_at, expires_at, approval_status, updated_at, search_result_total_count, decryption_target_count) "
                             + "VALUES (?, ?, 'java_fw_imglog', '{}', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'PENDING', CURRENT_TIMESTAMP, ?, ?)")) {
            ps.setLong(1, 601L);
            ps.setLong(2, 20260001L);
            ps.setInt(3, 55);
            ps.setInt(4, 4);
            ps.executeUpdate();
        }
        SearchHistoryListRequest request = newListRequest(20269999L);
        request.setUserId(20260001L);
        SearchHistoryListResponse resp = searchHistoryService.list(request);
        assertThat(resp.getData()).hasSize(1);
        assertThat(resp.getData().get(0).get("searchResultTotalCount")).isEqualTo(55);
        assertThat(resp.getData().get(0).get("decryptionTargetCount")).isEqualTo(4);
    }

    /** TC-07 (req 20260318): List API returns multiple rows; each row has both keys distinct, no overwriting. */
    @Test
    void list_withMultipleRows_eachRowHasDistinctSearchResultTotalCountAndDecryptionTargetCount() throws Exception {
        insertAppUser(dataSource, 20260001L, "alpha", "D01");
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO search_history (id, user_id, log_type, search_params, request_reason, requested_at, expires_at, approval_status, updated_at, search_result_total_count, decryption_target_count) "
                             + "VALUES (?, ?, 'java_fw_imglog', '{}', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'PENDING', CURRENT_TIMESTAMP, ?, ?)")) {
            ps.setLong(1, 701L);
            ps.setLong(2, 20260001L);
            ps.setInt(3, 48);
            ps.setInt(4, 37);
            ps.executeUpdate();
            ps.setLong(1, 702L);
            ps.setInt(3, 10);
            ps.setInt(4, 2);
            ps.executeUpdate();
        }
        SearchHistoryListRequest request = newListRequest(20269999L);
        request.setUserId(20260001L);
        SearchHistoryListResponse resp = searchHistoryService.list(request);
        assertThat(resp.getData()).hasSize(2);
        Map<String, Object> row1 = resp.getData().stream().filter(r -> 701L == ((Number) r.get("id")).longValue()).findFirst().orElseThrow();
        Map<String, Object> row2 = resp.getData().stream().filter(r -> 702L == ((Number) r.get("id")).longValue()).findFirst().orElseThrow();
        assertThat(row1.get("searchResultTotalCount")).isEqualTo(48);
        assertThat(row1.get("decryptionTargetCount")).isEqualTo(37);
        assertThat(row2.get("searchResultTotalCount")).isEqualTo(10);
        assertThat(row2.get("decryptionTargetCount")).isEqualTo(2);
    }

    @Test
    void getDetail_includesStoredCountFields() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO search_history (id, user_id, log_type, search_params, request_reason, requested_at, expires_at, approval_status, updated_at, search_result_total_count, decryption_target_count) "
                             + "VALUES (?, ?, 'java_fw_imglog', '{}', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'PENDING', CURRENT_TIMESTAMP, 88, 6)")) {
            ps.setLong(1, 602L);
            ps.setLong(2, 20260001L);
            ps.executeUpdate();
        }
        Map<String, Object> detail = searchHistoryService.getDetail(20260001L, 602L);
        assertThat(detail.get("searchResultTotalCount")).isEqualTo(88);
        assertThat(detail.get("decryptionTargetCount")).isEqualTo(6);
    }

    /** TC-02 (req 20260318): create() with null searchParams throws IllegalArgumentException → 400 from controller. */
    @Test
    void create_whenSearchParamsNull_throwsIllegalArgumentException() {
        SearchHistoryCreateRequest request = new SearchHistoryCreateRequest();
        request.setLogType("java_fw_imglog");
        request.setSearchParams(null);
        request.setRequestReason("사유");

        assertThatThrownBy(() -> searchHistoryService.create(20260001L, request))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("searchParams is required");
    }

    @Test
    void create_whenRequestReasonOver500_throwsIllegalArgumentException() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        SearchHistoryCreateRequest request = new SearchHistoryCreateRequest();
        request.setLogType("java_fw_imglog");
        request.setSearchParams(Map.of());
        request.setRequestReason("a".repeat(501));

        assertThatThrownBy(() -> searchHistoryService.create(20260001L, request))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("500");
    }

    /** TC-02: list requestedAtFrom/To → filtered. Req 20260317. */
    @Test
    void list_filtersByRequestedAtFromAndTo() throws Exception {
        insertAppUser(dataSource, 20260001L, "alpha", "D01");
        Instant t1 = Instant.now().minus(2, ChronoUnit.DAYS);
        Instant t2 = Instant.now().minus(1, ChronoUnit.DAYS);
        Instant t3 = Instant.now();
        insertSearchHistoryRow(dataSource, 201L, 20260001L, false, t1, null, "PENDING");
        insertSearchHistoryRow(dataSource, 202L, 20260001L, false, t2, null, "PENDING");
        insertSearchHistoryRow(dataSource, 203L, 20260001L, false, t3, null, "PENDING");

        java.time.format.DateTimeFormatter fmt = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        java.time.LocalDateTime t2Local = java.time.LocalDateTime.ofInstant(t2, java.time.ZoneId.systemDefault());
        SearchHistoryListRequest req = newListRequest(20269999L);
        req.setUserId(20260001L);
        req.setRequestedAtFrom(t2Local.minusHours(1).format(fmt));
        req.setRequestedAtTo(t2Local.plusHours(1).format(fmt));

        SearchHistoryListResponse resp = searchHistoryService.list(req);

        assertThat(resp.getData()).hasSize(1);
        assertThat(resp.getData().get(0).get("id")).isEqualTo(202L);
    }

    /** TC-03: list approvalStatus multi → IN filter. Req 20260317. */
    @Test
    void list_filtersByApprovalStatusesIn() throws Exception {
        insertAppUser(dataSource, 20260001L, "alpha", "D01");
        insertSearchHistoryRow(dataSource, 211L, 20260001L, false, Instant.now(), null, "PENDING");
        insertSearchHistoryRow(dataSource, 212L, 20260001L, false, Instant.now(), null, "APPROVED");
        insertSearchHistoryRow(dataSource, 213L, 20260001L, false, Instant.now(), null, "REJECTED");

        SearchHistoryListRequest req = newListRequest(20269999L);
        req.setUserId(20260001L);
        req.setApprovalStatuses(List.of("PENDING", "APPROVED"));
        SearchHistoryListResponse resp = searchHistoryService.list(req);

        assertThat(resp.getData()).hasSize(2);
        assertThat(resp.getData()).extracting(r -> r.get("approvalStatus")).containsExactlyInAnyOrder("PENDING", "APPROVED");
    }

    /** Invalid requestedAtFrom format → IllegalArgumentException (req 20260317: validation error). */
    @Test
    void list_whenRequestedAtFromInvalidFormat_throwsIllegalArgumentException() throws Exception {
        insertAppUser(dataSource, 20260001L, "alpha", "D01");
        insertSearchHistoryRow(dataSource, 230L, 20260001L, false, Instant.now(), null, "PENDING");

        SearchHistoryListRequest req = newListRequest(20269999L);
        req.setUserId(20260001L);
        req.setRequestedAtFrom("2026-03-01"); // missing time part

        assertThatThrownBy(() -> searchHistoryService.list(req))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("yyyy-MM-dd HH:mm:ss");
    }

    /** TC-04: list requestReason → ILIKE. Req 20260317. */
    @Test
    void list_filtersByRequestReasonIlike() throws Exception {
        insertAppUser(dataSource, 20260001L, "alpha", "D01");
        insertSearchHistoryRow(dataSource, 221L, 20260001L, false, Instant.now(), "검색 테스트 사유", "PENDING");
        insertSearchHistoryRow(dataSource, 222L, 20260001L, false, Instant.now(), "다른 내용", "PENDING");
        insertSearchHistoryRow(dataSource, 223L, 20260001L, false, Instant.now(), "검색 키워드 포함", "PENDING");

        SearchHistoryListRequest req = newListRequest(20269999L);
        req.setUserId(20260001L);
        req.setRequestReason("검색");
        SearchHistoryListResponse resp = searchHistoryService.list(req);

        assertThat(resp.getData()).hasSize(2);
        assertThat(resp.getData()).extracting(r -> r.get("id")).containsExactlyInAnyOrder(221L, 223L);
        assertThat(resp.getData()).allMatch(r -> r.get("requestReason") != null && r.get("requestReason").toString().contains("검색"));
    }

    @Test
    void getDetail_allowsRequesterOwnRow() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        long id = insertSearchHistoryRow(dataSource, 101L, 20260001L, false);

        Map<String, Object> detail = searchHistoryService.getDetail(20260001L, id);

        assertThat(detail).isNotNull();
        assertThat(detail.get("id")).isEqualTo(id);
        assertThat(detail.get("logType")).isEqualTo("java_fw_imglog");
    }

    @Test
    void getDetail_includesRequestReason() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        long id = insertSearchHistoryRow(dataSource, 105L, 20260001L, false, Instant.now(), "상세 조회 요청 사유", "PENDING");

        Map<String, Object> detail = searchHistoryService.getDetail(20260001L, id);

        assertThat(detail).isNotNull();
        assertThat(detail.get("requestReason")).isEqualTo("상세 조회 요청 사유");
    }

    // ---- getDetail decryptionRequestedRows / decryptionRequestedCount (req 20260318) ----

    /** TC-01: getDetail when APPROVED returns decryptionRequestedRows and decryptionRequestedCount. */
    @Test
    void getDetail_whenApproved_returnsDecryptionRequestedRowsAndCount() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        long id = insertSearchHistoryRow(dataSource, 501L, 20260001L, false, Instant.now(), null, "APPROVED");
        insertApprovedRows(dataSource, 501L, "java_fw_imglog", List.of("guid-d1", "guid-d2"));

        Map<String, Map<String, String>> resolution = new LinkedHashMap<>();
        resolution.put("guid-d1", Map.of("application", "app1", "serviceGroup", "sg1"));
        resolution.put("guid-d2", Map.of("application", "app2", "serviceGroup", "sg2"));
        stubLogDbService.setApplicationServiceGroupByGuids(resolution);

        Map<String, Object> detail = searchHistoryService.getDetail(20260001L, id);

        assertThat(detail).isNotNull();
        assertThat(detail.get("approvalStatus")).isEqualTo("APPROVED");
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> rows = (List<Map<String, Object>>) detail.get("decryptionRequestedRows");
        assertThat(rows).isNotNull().hasSize(2);
        assertThat(rows.get(0)).containsEntry("guid", "guid-d1").containsEntry("application", "app1").containsEntry("serviceGroup", "sg1");
        assertThat(rows.get(1)).containsEntry("guid", "guid-d2").containsEntry("application", "app2").containsEntry("serviceGroup", "sg2");
        assertThat(detail.get("decryptionRequestedCount")).isEqualTo(2);
    }

    /** TC-02: PENDING/REJECTED/EXPIRED — same collect-from-search as approve; rows + count from stub searchLogs. */
    @Test
    void getDetail_whenPendingRejectedExpired_rerunsSearchAndReturnsDecryptionRequestedRows() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        Map<String, Object> r1 = new LinkedHashMap<>();
        r1.put("guid", "g-pend-1");
        r1.put("datastring", "{\"p\":\"[" + LONG_ENC_PAYLOAD + "]\"}");
        Map<String, Object> r2 = new LinkedHashMap<>();
        r2.put("guid", "g-pend-2");
        r2.put("datastring", "{\"p\":\"[" + LONG_ENC_PAYLOAD + "x]\"}"); // 33 chars, still encrypted-style
        stubLogDbService.setSearchLogsData(List.of(r1, r2));
        stubLogDbService.setApplicationServiceGroupByGuids(Map.of(
                "g-pend-1", Map.of("application", "AppA", "serviceGroup", "SgA"),
                "g-pend-2", Map.of("application", "AppB", "serviceGroup", "SgB")));

        long idPending = insertSearchHistoryRow(dataSource, 502L, 20260001L, false, Instant.now(), null, "PENDING", "{}");
        long idRejected = insertSearchHistoryRow(dataSource, 503L, 20260001L, false, Instant.now(), null, "REJECTED", "{}");
        long idExpired = insertSearchHistoryRow(dataSource, 504L, 20260001L, true, Instant.now().minusSeconds(86400), null, "EXPIRED", "{}");

        for (long hid : List.of(idPending, idRejected, idExpired)) {
            Map<String, Object> d = searchHistoryService.getDetail(20260001L, hid);
            assertThat(d.get("decryptionRequestedCount")).isEqualTo(2);
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> rows = (List<Map<String, Object>>) d.get("decryptionRequestedRows");
            assertThat(rows).hasSize(2);
            assertThat(rows).anyMatch(m -> "g-pend-1".equals(m.get("guid")) && "AppA".equals(m.get("application")));
            assertThat(rows).anyMatch(m -> "g-pend-2".equals(m.get("guid")) && "AppB".equals(m.get("application")));
        }
    }

    /** PENDING with no encrypted rows in search result → empty list, count 0. */
    @Test
    void getDetail_whenPending_noEncryptedInSearch_returnsEmptyDecryptionRows() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        Map<String, Object> plain = new LinkedHashMap<>();
        plain.put("guid", "g-plain");
        plain.put("datastring", "");
        plain.put("headerstring", "");
        stubLogDbService.setSearchLogsData(List.of(plain));
        long id = insertSearchHistoryRow(dataSource, 507L, 20260001L, false, Instant.now(), null, "PENDING", "{}");
        Map<String, Object> d = searchHistoryService.getDetail(20260001L, id);
        assertThat(d.get("decryptionRequestedCount")).isEqualTo(0);
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> rows = (List<Map<String, Object>>) d.get("decryptionRequestedRows");
        assertThat(rows).isEmpty();
    }

    /** APPROVED with empty search_history_approved_row falls back to collect-from-search. */
    @Test
    void getDetail_whenApproved_emptySnapshot_fallsBackToSearchRows() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        Map<String, Object> r = new LinkedHashMap<>();
        r.put("guid", "g-fallback");
        r.put("headerstring", "{\"h\":\"[" + LONG_ENC_PAYLOAD + "]\"}");
        stubLogDbService.setSearchLogsData(List.of(r));
        stubLogDbService.setApplicationServiceGroupByGuids(Map.of("g-fallback", Map.of("application", "FbApp", "serviceGroup", "FbSg")));
        long id = insertSearchHistoryRow(dataSource, 508L, 20260001L, false, Instant.now(), null, "APPROVED", "{}");
        Map<String, Object> d = searchHistoryService.getDetail(20260001L, id);
        assertThat(d.get("decryptionRequestedCount")).isEqualTo(1);
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> rows = (List<Map<String, Object>>) d.get("decryptionRequestedRows");
        assertThat(rows).hasSize(1);
        assertThat(rows.get(0)).containsEntry("guid", "g-fallback").containsEntry("application", "FbApp");
    }

    /** TC-03: getDetail when APPROVED but log DB fails or guid not in imagelog → 200, rows have guid, application/serviceGroup null, count correct. */
    @Test
    void getDetail_whenApprovedButLogDbUnavailable_returnsRowsWithGuidAndNullAppServiceGroup() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        long id = insertSearchHistoryRow(dataSource, 505L, 20260001L, false, Instant.now(), null, "APPROVED");
        insertApprovedRows(dataSource, 505L, "java_fw_imglog", List.of("guid-missing", "guid-also-missing"));

        stubLogDbService.setApplicationServiceGroupByGuids(Collections.emptyMap());

        Map<String, Object> detail = searchHistoryService.getDetail(20260001L, id);

        assertThat(detail).isNotNull();
        assertThat(detail.get("approvalStatus")).isEqualTo("APPROVED");
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> rows = (List<Map<String, Object>>) detail.get("decryptionRequestedRows");
        assertThat(rows).isNotNull().hasSize(2);
        assertThat(rows).allMatch(r -> r.get("application") == null && r.get("serviceGroup") == null && r.get("guid") != null);
        assertThat(rows).extracting(r -> r.get("guid")).containsExactlyInAnyOrder("guid-missing", "guid-also-missing");
        assertThat(detail.get("decryptionRequestedCount")).isEqualTo(2);
    }

    private static void insertApprovedRows(DataSource ds, long searchHistoryId, String logType, List<String> rowIds) throws Exception {
        try (Connection conn = ds.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO search_history_approved_row (search_history_id, log_type, row_id, row_status) VALUES (?, ?, ?, '')")) {
            for (String rowId : rowIds) {
                ps.setLong(1, searchHistoryId);
                ps.setString(2, logType);
                ps.setString(3, rowId);
                ps.executeUpdate();
            }
        }
    }

    @Test
    void reRequest_allowsRequesterOwnExpiredRow() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        long id = insertSearchHistoryRow(dataSource, 102L, 20260001L, true);

        Map<String, Object> result = searchHistoryService.reRequest(20260001L, id);

        assertThat(result).isNotNull();
        assertThat(result.get("id")).isEqualTo(id);
        assertThat(result.get("approvalStatus")).isEqualTo("PENDING");
    }

    @Test
    void getDetail_returns403WhenNotRequester() throws Exception {
        insertAppUser(dataSource, 20260001L, "ownerUser", "D01");
        insertAppUser(dataSource, 20260002L, "otherUser", "D01");
        long id = insertSearchHistoryRow(dataSource, 103L, 20260001L, false);

        assertThatThrownBy(() -> searchHistoryService.getDetail(20260002L, id, ScreenConstants.SEARCH_HISTORY, false,
                        Map.of("search-history", "self"), null))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getHttpStatus()).isEqualTo(HttpStatus.FORBIDDEN);
                    assertThat(ex.getErrorCode()).isEqualTo("FUNCTION_NOT_ALLOWED");
                });
    }

    @Test
    void reRequest_returns403WhenNotRequester() throws Exception {
        insertAppUser(dataSource, 20260001L, "ownerUser", "D01");
        insertAppUser(dataSource, 20260002L, "otherUser", "D01");
        long id = insertSearchHistoryRow(dataSource, 104L, 20260001L, true);

        assertThatThrownBy(() -> searchHistoryService.reRequest(20260002L, id))
                .isInstanceOf(CustomException.class)
                .satisfies(e -> {
                    CustomException ex = (CustomException) e;
                    assertThat(ex.getHttpStatus()).isEqualTo(HttpStatus.FORBIDDEN);
                    assertThat(ex.getErrorCode()).isEqualTo("FUNCTION_NOT_ALLOWED");
                });
    }

    @Test
    void isValidApprovalForUser_returnsTrueWhenRowOwnedByUserAndApprovedAndNotExpired() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        Timestamp future = Timestamp.from(Instant.now().plusSeconds(86400));
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO search_history (id, user_id, log_type, search_params, approval_status, requested_at, expires_at, updated_at) VALUES (?, ?, ?, '{}', 'APPROVED', CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP)")) {
            ps.setLong(1, 200L);
            ps.setObject(2, 20260001L);
            ps.setString(3, "java_fw_imglog");
            ps.setTimestamp(4, future);
            ps.executeUpdate();
        }
        boolean result = searchHistoryService.isValidApprovalForUser(200L, 20260001L);
        assertThat(result).isTrue();
    }

    @Test
    void isValidApprovalForUser_returnsFalseWhenUserDoesNotOwnRow() throws Exception {
        insertAppUser(dataSource, 20260001L, "owner", "D01");
        insertAppUser(dataSource, 20260002L, "other", "D01");
        Timestamp future = Timestamp.from(Instant.now().plusSeconds(86400));
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO search_history (id, user_id, log_type, search_params, approval_status, requested_at, expires_at, updated_at) VALUES (?, ?, ?, '{}', 'APPROVED', CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP)")) {
            ps.setLong(1, 201L);
            ps.setObject(2, 20260001L);
            ps.setString(3, "java_fw_imglog");
            ps.setTimestamp(4, future);
            ps.executeUpdate();
        }
        boolean result = searchHistoryService.isValidApprovalForUser(201L, 20260002L);
        assertThat(result).isFalse();
    }

    /** TC-04: APPROVED but expired → false. Req 20260317-decrypt-execution-user-id-fix. */
    @Test
    void isValidApprovalForUser_returnsFalseWhenExpired() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        Timestamp past = Timestamp.from(Instant.now().minusSeconds(3600));
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO search_history (id, user_id, log_type, search_params, approval_status, requested_at, expires_at, updated_at) VALUES (?, ?, ?, '{}', 'APPROVED', CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP)")) {
            ps.setLong(1, 202L);
            ps.setObject(2, 20260001L);
            ps.setString(3, "java_fw_imglog");
            ps.setTimestamp(4, past);
            ps.executeUpdate();
        }
        boolean result = searchHistoryService.isValidApprovalForUser(202L, 20260001L);
        assertThat(result).isFalse();
    }

    /** search_history not APPROVED (e.g. PENDING) → false. Req 20260317-decrypt-execution-user-id-fix. */
    @Test
    void isValidApprovalForUser_returnsFalseWhenStatusNotApproved() throws Exception {
        insertAppUser(dataSource, 20260001L, "user1", "D01");
        Timestamp future = Timestamp.from(Instant.now().plusSeconds(86400));
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO search_history (id, user_id, log_type, search_params, approval_status, requested_at, expires_at, updated_at) VALUES (?, ?, ?, '{}', 'PENDING', CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP)")) {
            ps.setLong(1, 203L);
            ps.setObject(2, 20260001L);
            ps.setString(3, "java_fw_imglog");
            ps.setTimestamp(4, future);
            ps.executeUpdate();
        }
        boolean result = searchHistoryService.isValidApprovalForUser(203L, 20260001L);
        assertThat(result).isFalse();
    }

    // ---- listPending scope (req 20260305-pending-approvals-scope) TC-01, TC-02, TC-03 ----

    /** TC-01: scope self → only rows where requester = current user (approverUserId). */
    @Test
    void listPending_scopeSelf_returnsOnlyRowsWhereRequesterEqualsCurrentUser() throws Exception {
        clearAllTables(dataSource);
        insertAppUser(dataSource, 20260001L, "approver1", "D01");
        insertAppUser(dataSource, 20260002L, "otherUser", "D01");
        insertPendingRow(dataSource, 201L, 20260001L);
        insertPendingRow(dataSource, 202L, 20260002L);
        insertPendingRow(dataSource, 203L, 20260001L);

        SearchHistoryListResponse resp = searchHistoryService.listPending(20260001L, false, 1, 20, false, null);

        assertThat(resp.getData()).hasSize(2);
        assertThat(resp.getData()).allMatch(row -> "approver1".equals(row.get("requester")));
        assertThat(resp.getPagination().getTotalCount()).isEqualTo(2);
    }

    /** TC-02 / TC-03: scope team → only rows where requester in allowedUserIds (numeric app_user.id). */
    @Test
    void listPending_scopeTeam_returnsOnlyRowsWhereRequesterInAllowedUserIds() throws Exception {
        clearAllTables(dataSource);
        insertAppUser(dataSource, 20260001L, "userA", "D01");
        insertAppUser(dataSource, 20260002L, "userB", "D01");
        insertAppUser(dataSource, 20260003L, "userC", "D02");
        insertPendingRow(dataSource, 301L, 20260001L);
        insertPendingRow(dataSource, 302L, 20260002L);
        insertPendingRow(dataSource, 303L, 20260003L);

        List<Long> teamUserIds = List.of(20260001L, 20260002L);
        SearchHistoryListResponse resp = searchHistoryService.listPending(20260001L, false, 1, 20, false, teamUserIds);

        assertThat(resp.getData()).hasSize(2);
        assertThat(resp.getData()).extracting(row -> row.get("requester")).containsExactlyInAnyOrder("userA", "userB");
        assertThat(resp.getPagination().getTotalCount()).isEqualTo(2);
    }

    /** TC-03: scope all → all PENDING rows that canApproveForRequester allows. */
    @Test
    void listPending_scopeAll_returnsAllApprovableRows() throws Exception {
        clearAllTables(dataSource);
        insertAppUser(dataSource, 20260001L, "req1", "D01");
        insertAppUser(dataSource, 20260002L, "req2", "D01");
        insertAppUser(dataSource, 20260003L, "req3", "D01");
        insertPendingRow(dataSource, 401L, 20260001L);
        insertPendingRow(dataSource, 402L, 20260002L);
        insertPendingRow(dataSource, 403L, 20260003L);

        SearchHistoryListResponse resp = searchHistoryService.listPending(20260001L, false, 1, 20, true, null);

        assertThat(resp.getData()).hasSize(3);
        assertThat(resp.getPagination().getTotalCount()).isEqualTo(3);
    }

    @Test
    void listPending_scopeSelf_withNoOwnRequests_returnsEmpty() throws Exception {
        clearAllTables(dataSource);
        insertAppUser(dataSource, 20260001L, "approver1", "D01");
        insertAppUser(dataSource, 20260002L, "otherUser", "D01");
        insertPendingRow(dataSource, 501L, 20260002L);

        SearchHistoryListResponse resp = searchHistoryService.listPending(20260001L, false, 1, 20, false, null);

        assertThat(resp.getData()).isEmpty();
        assertThat(resp.getPagination().getTotalCount()).isEqualTo(0);
    }

    private static void clearAllTables(DataSource ds) throws Exception {
        try (Connection conn = ds.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM user_decryption_allowed");
            stmt.execute("DELETE FROM search_history_approved_row");
            stmt.execute("DELETE FROM search_history");
            stmt.execute("DELETE FROM app_user");
        }
    }

    private static void insertPendingRow(DataSource ds, long id, long requesterUserId) throws Exception {
        Timestamp requestedAt = Timestamp.from(Instant.now());
        Timestamp expiresAt = Timestamp.from(Instant.now().plusSeconds(86400));
        try (Connection conn = ds.getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO search_history (id, user_id, log_type, search_params, approval_status, requested_at, expires_at, updated_at) VALUES (?, ?, ?, '{}', 'PENDING', ?, ?, CURRENT_TIMESTAMP)")) {
            ps.setLong(1, id);
            ps.setObject(2, requesterUserId);
            ps.setString(3, "java_fw_imglog");
            ps.setTimestamp(4, requestedAt);
            ps.setTimestamp(5, expiresAt);
            ps.executeUpdate();
        }
    }

}
