package com.logmng.service;

import com.logmng.dto.response.DepartmentNodeWithUsersResponse;
import com.logmng.dto.response.UserPermissionSummary;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * TC-03: GET /api/departments/user-permission-hierarchy — each user has userId and userName;
 * userName = app_user.name when set, else userId.
 */
class UserPermissionHierarchyServiceTest {

    private static final String H2_URL = "jdbc:h2:mem:uph_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH";

    private DataSource dataSource;
    private UserPermissionHierarchyService service;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = createH2DataSource();
        clearAllTables();
        service = new UserPermissionHierarchyService(dataSource, new DepartmentService(dataSource), false);
    }

    private static DataSource createH2DataSource() throws Exception {
        Class.forName("org.h2.Driver");
        try (Connection conn = java.sql.DriverManager.getConnection(H2_URL);
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS department (" +
                    "code VARCHAR(50) PRIMARY KEY, parent_code VARCHAR(50), name VARCHAR(100), sort_order INT)");
            stmt.execute("CREATE TABLE IF NOT EXISTS app_user (" +
                    "id BIGINT, username VARCHAR(100) PRIMARY KEY, name VARCHAR(200), role VARCHAR(50), department_code VARCHAR(50), position VARCHAR(100), rank VARCHAR(100), is_system_admin BOOLEAN, employee_number VARCHAR(100), deleted_at TIMESTAMP NULL)");
            stmt.execute("CREATE TABLE IF NOT EXISTS permission_group (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(50), name VARCHAR(100), sort_order INT)");
            stmt.execute("CREATE TABLE IF NOT EXISTS app_user_permission_group (" +
                    "user_id VARCHAR(100), permission_group_id BIGINT)");
        }
        org.h2.jdbcx.JdbcDataSource ds = new org.h2.jdbcx.JdbcDataSource();
        ds.setURL(H2_URL);
        return ds;
    }

    private void clearAllTables() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM app_user_permission_group");
            stmt.execute("DELETE FROM app_user");
            stmt.execute("DELETE FROM permission_group");
            stmt.execute("DELETE FROM department");
        }
    }

    private void insertDepartment(String code, String name, int sortOrder) throws Exception {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO department (code, parent_code, name, sort_order) VALUES (?, NULL, ?, ?)")) {
            ps.setString(1, code);
            ps.setString(2, name);
            ps.setInt(3, sortOrder);
            ps.executeUpdate();
        }
    }

    private long nextUserId = 20260001L;

    private void insertUser(String username, String name, String departmentCode) throws Exception {
        insertUser(username, name, departmentCode, null);
    }

    private void insertUser(String username, String name, String departmentCode, String employeeNumber) throws Exception {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO app_user (id, username, name, role, department_code, position, rank, is_system_admin, employee_number) VALUES (?, ?, ?, 'user', ?, NULL, NULL, FALSE, ?)")) {
            ps.setLong(1, nextUserId++);
            ps.setString(2, username);
            ps.setString(3, name);
            ps.setString(4, departmentCode);
            if (employeeNumber != null) {
                ps.setString(5, employeeNumber);
            } else {
                ps.setObject(5, null, java.sql.Types.VARCHAR);
            }
            ps.executeUpdate();
        }
    }

    @Test
    void getHierarchyFlat_returnsUserIdAndUserName_perUser() throws Exception {
        insertDepartment("D01", "Team A", 1);
        insertUser("user1", "홍길동", "D01", "20261001");
        insertUser("user2", null, "D01");

        List<DepartmentNodeWithUsersResponse> flat = service.getHierarchyFlat();

        assertThat(flat).isNotEmpty();
        DepartmentNodeWithUsersResponse dept = flat.stream().filter(n -> "D01".equals(n.getCode())).findFirst().orElse(null);
        assertThat(dept).isNotNull();
        assertThat(dept.getUsers()).hasSize(2);

        UserPermissionSummary withName = dept.getUsers().stream().filter(u -> "홍길동".equals(u.getUserName())).findFirst().orElse(null);
        assertThat(withName).isNotNull();
        assertThat(withName.getUserId()).isNotNull();
        assertThat(withName.getUserName()).isEqualTo("홍길동");
        assertThat(withName.getEmployeeNumber()).isEqualTo("20261001");

        UserPermissionSummary withoutName = dept.getUsers().stream().filter(u -> u.getUserName() != null && u.getUserName().equals("user2")).findFirst().orElse(null);
        assertThat(withoutName).isNotNull();
        assertThat(withoutName.getUserId()).isNotNull();
        assertThat(withoutName.getUserName()).isEqualTo("user2");
        assertThat(withoutName.getEmployeeNumber()).isNull();
    }

    @Test
    void getHierarchyFlat_includesNullDepartmentUsersInUnassignedBucket() throws Exception {
        insertDepartment("D01", "Team A", 1);
        insertUser("inDept", "부서있음", "D01");
        insertUser("noDept", "미배치", null);

        List<DepartmentNodeWithUsersResponse> flat = service.getHierarchyFlat();

        DepartmentNodeWithUsersResponse unassigned = flat.stream()
                .filter(n -> UserPermissionHierarchyService.UNASSIGNED_DEPARTMENT_CODE.equals(n.getCode()))
                .findFirst().orElse(null);
        assertThat(unassigned).isNotNull();
        assertThat(unassigned.getUsers()).hasSize(1);
        assertThat(unassigned.getUsers().get(0).getUserName()).isEqualTo("미배치");
    }
}
