package com.logmng.service;

import com.logmng.dto.response.LoginResponse;
import com.logmng.exception.CustomException;
import com.logmng.repository.UserActivityAccessAuditRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Privileged reveal + access-audit insert (H2).
 */
class UserActivityLogPrivilegedRevealTest {

    private static final String H2_URL = "jdbc:h2:mem:activity_audit_ev;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH";

    private DataSource dataSource;
    private UserActivityLogService service;

    @BeforeEach
    void setUp() throws Exception {
        Class.forName("org.h2.Driver");
        try (Connection conn = java.sql.DriverManager.getConnection(H2_URL);
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS app_user (" +
                    "id BIGINT PRIMARY KEY, username VARCHAR(100) NOT NULL, department_code VARCHAR(50))");
            stmt.execute("CREATE TABLE IF NOT EXISTS user_activity_log (" +
                    "id BIGINT PRIMARY KEY, user_id VARCHAR(100), username VARCHAR(100), action_type VARCHAR(50), " +
                    "action_detail CLOB, ip_address VARCHAR(100), user_agent VARCHAR(255), request_method VARCHAR(10), " +
                    "request_path VARCHAR(255), request_params CLOB, response_status INT, response_time_ms INT, " +
                    "success BOOLEAN, error_message VARCHAR(500), created_at TIMESTAMP, updated_at TIMESTAMP)");
            stmt.execute("CREATE TABLE IF NOT EXISTS user_activity_access_audit (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, accessor_user_id BIGINT NOT NULL, " +
                    "target_activity_log_id BIGINT, access_type VARCHAR(64) NOT NULL, " +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ip_address VARCHAR(45), user_agent TEXT)");
        }
        org.h2.jdbcx.JdbcDataSource ds = new org.h2.jdbcx.JdbcDataSource();
        ds.setURL(H2_URL);
        dataSource = ds;

        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("DELETE FROM user_activity_access_audit");
            st.execute("DELETE FROM user_activity_log");
            st.execute("DELETE FROM app_user");
        }
        insertUser(20260001L, "auditor", "D01");
        insertUser(20260002L, "other", "D02");
        insertCopyLog(500L, "auditor", "Auditor",
                "{\"copyPayload\":{\"text\":\"SECRET_FULL_BODY\",\"was_truncated\":false,\"length\":16}}");

        service = new UserActivityLogService(dataSource, new UserActivityAccessAuditRepository(dataSource));
    }

    private void insertUser(long id, String username, String dept) throws Exception {
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO app_user (id, username, department_code) VALUES (?, ?, ?)")) {
            ps.setLong(1, id);
            ps.setString(2, username);
            ps.setString(3, dept);
            ps.executeUpdate();
        }
    }

    private void insertCopyLog(long id, String userId, String username, String actionDetailJson) throws Exception {
        Timestamp now = Timestamp.from(Instant.parse("2026-04-01T12:00:00Z"));
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO user_activity_log " +
                             "(id, user_id, username, action_type, action_detail, ip_address, user_agent, request_method, request_path, request_params, response_status, response_time_ms, success, error_message, created_at, updated_at) " +
                             "VALUES (?, ?, ?, 'IN_APP_COPY', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")) {
            ps.setLong(1, id);
            ps.setString(2, userId);
            ps.setString(3, username);
            ps.setString(4, actionDetailJson);
            ps.setString(5, "10.0.0.1");
            ps.setString(6, "JUnit");
            ps.setString(7, "POST");
            ps.setString(8, "/x");
            ps.setString(9, "{}");
            ps.setInt(10, 200);
            ps.setInt(11, 1);
            ps.setBoolean(12, true);
            ps.setString(13, null);
            ps.setTimestamp(14, now);
            ps.setTimestamp(15, now);
            ps.executeUpdate();
        }
    }

    @Test
    void privilegedReveal_insertsAuditThenReturnsFullText() throws Exception {
        LoginResponse admin = new LoginResponse();
        admin.setUsername("auditor");
        admin.setUserId(20260001L);
        admin.setIsSystemAdmin(true);

        Map<String, Object> data = service.privilegedRevealCopyBody(
                500L, "COPY_BODY_FULL", admin, "127.0.0.1", "JUnit",
                null, List.of("auditor", "other"));

        assertThat(data.get("copyBodyFull")).isEqualTo("SECRET_FULL_BODY");
        assertThat(countAuditRows()).isEqualTo(1L);
    }

    @Test
    void privilegedReveal_forbiddenWithoutPrivilege() {
        LoginResponse u = new LoginResponse();
        u.setUsername("auditor");
        u.setUserId(20260001L);
        u.setIsSystemAdmin(false);
        u.setAllowedScreenIds(List.of("activity-log"));

        assertThatThrownBy(() -> service.privilegedRevealCopyBody(
                500L, "COPY_BODY_FULL", u, "127.0.0.1", "JUnit",
                null, List.of("auditor", "other")))
                .isInstanceOf(CustomException.class)
                .hasFieldOrPropertyWithValue("errorCode", "REVEAL_NOT_ALLOWED");
    }

    private long countAuditRows() throws Exception {
        try (Connection c = dataSource.getConnection();
             ResultSet rs = c.createStatement().executeQuery("SELECT COUNT(*) FROM user_activity_access_audit")) {
            return rs.next() ? rs.getLong(1) : 0L;
        }
    }
}
