#!/usr/bin/env bash
#
# LogMng — single offline installer & launcher (no npm/mvn/internet on this host).
# Run from the root of the extracted offline bundle (same directory as bin/, db/).
#
# Usage: ./install-offline.sh check|db|configure|start|stop|status|all
#
set -euo pipefail

BUNDLE_ROOT="$(cd "$(dirname "$0")" && pwd)"
VAR_DIR="$BUNDLE_ROOT/var"
LOG_DIR="$VAR_DIR/log"
RUN_DIR="$VAR_DIR/run"
ENV_FILE="$VAR_DIR/logmng.env"

BACKEND_JAR="$BUNDLE_ROOT/bin/backend/logmng-backend-1.0.0.jar"
STATIC_JAR="$BUNDLE_ROOT/bin/frontend/logmng-static-server-1.0.0.jar"
WWW_DIR="$BUNDLE_ROOT/bin/frontend/www"
DB_SETUP="$BUNDLE_ROOT/db/setup.sh"

lc() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

prompt() {
  local label="$1"
  local def="$2"
  local val
  read -r -p "${label} [${def}]: " val || true
  if [[ -z "${val}" ]]; then
    echo "$def"
  else
    echo "$val"
  fi
}

prompt_secret() {
  local label="$1"
  local val
  read -r -s -p "${label}: " val || true
  echo ""
  echo "${val:-}"
}

ensure_dirs() {
  mkdir -p "$LOG_DIR" "$RUN_DIR"
}

write_env_file() {
  local path="$1"
  umask 077
  cat >"$path" <<EOF
# Generated by install-offline.sh — contains secrets.
export SERVER_PORT="${SERVER_PORT}"
export SPRING_DATASOURCE_URL="${SPRING_DATASOURCE_URL}"
export SPRING_DATASOURCE_USERNAME="${SPRING_DATASOURCE_USERNAME}"
export SPRING_DATASOURCE_PASSWORD="${SPRING_DATASOURCE_PASSWORD}"
export APP_DB_SCHEMA_SYS="${APP_DB_SCHEMA_SYS}"
export APP_DB_SCHEMA_PB="${APP_DB_SCHEMA_PB}"
export APP_DB_SCHEMA_IMAGELOG="${APP_DB_SCHEMA_IMAGELOG}"
export APP_DATASOURCE_IMAGELOG_URL="${APP_DATASOURCE_IMAGELOG_URL:-}"
export APP_DATASOURCE_IMAGELOG_USERNAME="${APP_DATASOURCE_IMAGELOG_USERNAME:-}"
export APP_DATASOURCE_IMAGELOG_PASSWORD="${APP_DATASOURCE_IMAGELOG_PASSWORD:-}"
export CORS_ALLOWED_ORIGINS="${CORS_ALLOWED_ORIGINS}"
export FRONTEND_PORT="${FRONTEND_PORT}"
EOF
  chmod 600 "$path"
  echo "Wrote $path (mode 600)"
}

cmd_check() {
  echo "=== Offline bundle check ==="
  echo "Root: $BUNDLE_ROOT"
  local ok=1
  if ! command -v java >/dev/null 2>&1; then
    echo "[FAIL] java not found — install JRE/JDK 17+"
    ok=0
  else
    echo "[OK] java: $(command -v java)"
    java -version 2>&1 | head -1 || true
  fi
  if ! command -v psql >/dev/null 2>&1; then
    echo "[WARN] psql not found — DB step (db/all) will fail until client is installed"
  else
    echo "[OK] psql: $(command -v psql)"
  fi
  [[ -f "$BACKEND_JAR" ]] && echo "[OK] backend JAR" || { echo "[FAIL] missing $BACKEND_JAR"; ok=0; }
  [[ -f "$STATIC_JAR" ]] && echo "[OK] static server JAR" || { echo "[FAIL] missing $STATIC_JAR"; ok=0; }
  [[ -f "$WWW_DIR/index.html" ]] && echo "[OK] frontend www/index.html" || { echo "[FAIL] missing $WWW_DIR/index.html"; ok=0; }
  [[ -f "$DB_SETUP" ]] && echo "[OK] db/setup.sh" || { echo "[FAIL] missing $DB_SETUP"; ok=0; }
  return $((1 - ok))
}

cmd_db() {
  echo "=== Database setup (bundled db/setup.sh) ==="
  if [[ ! -f "$DB_SETUP" ]]; then
    echo "Missing $DB_SETUP" >&2
    exit 1
  fi
  if [[ "$(uname -s)" != "Linux" ]]; then
    echo "Warning: expected Linux server (found: $(uname -s))"
  fi
  echo ""
  echo "  1) Full DDL + migrations + init-data (new DB)"
  echo "  2) sys_only (PB already in SCHEMA_PB; new SCHEMA_SYS only)"
  echo "  3) Skip DB script (already provisioned)"
  echo ""
  local dchoice
  read -r -p "Select [1-3]: " dchoice || true
  if [[ "$dchoice" == "3" ]]; then
    echo "Skipped."
    return 0
  fi
  export DB_SUPERUSER="$(prompt "PostgreSQL superuser" "postgres")"
  echo "Superuser password (empty if peer/trust):"
  local sp
  sp="$(prompt_secret "PGPASSWORD_SUPER")"
  [[ -n "$sp" ]] && export PGPASSWORD_SUPER="$sp"

  export DB_HOST="$(prompt "DB host" "localhost")"
  export DB_PORT="$(prompt "DB port" "5432")"
  export DB_NAME="$(prompt "Database name (A)" "logmng")"
  export DB_USER="$(prompt "App DB user" "logmng")"
  export DB_PASSWORD="$(prompt "App DB password" "logmng123")"
  export DB_A_NAME="$DB_NAME"
  export DB_B_NAME="$(prompt "ImageLog DB (B, same as A for single DB)" "$DB_NAME")"
  export SCHEMA_SYS="$(prompt "SCHEMA_SYS" "public")"
  export SCHEMA_PB="$(prompt "SCHEMA_PB" "public")"
  export SCHEMA_IMAGELOG="$(prompt "SCHEMA_IMAGELOG (on B)" "public")"

  if [[ "$dchoice" == "2" ]]; then
    echo ""
    echo "sys_only: PB DDL skipped. See README-OFFLINE.md / DB_SETUP_GUIDE if unsure."
    read -r -p "Continue? [y/N]: " ok || true
    [[ "$(lc "${ok:-}")" == "y" ]] || exit 1
    export SETUP_MODE=sys_only
  else
    export SETUP_MODE=full
  fi

  (cd "$BUNDLE_ROOT/db" && bash ./setup.sh)
  echo "DB step done."
}

cmd_configure() {
  echo "=== Application environment ($ENV_FILE) ==="
  ensure_dirs
  local db_host db_port db_name db_user db_password
  db_host="$(prompt "DB host (for JDBC)" "localhost")"
  db_port="$(prompt "DB port" "5432")"
  db_name="$(prompt "Database name (primary A)" "logmng")"
  db_user="$(prompt "JDBC username" "logmng")"
  db_password="$(prompt "JDBC password" "logmng123")"

  export SERVER_PORT="$(prompt "Backend HTTP port" "9200")"
  export FRONTEND_PORT="$(prompt "Frontend static port" "3001")"
  export SPRING_DATASOURCE_URL="jdbc:postgresql://${db_host}:${db_port}/${db_name}"
  export SPRING_DATASOURCE_USERNAME="$db_user"
  export SPRING_DATASOURCE_PASSWORD="$db_password"
  export APP_DB_SCHEMA_SYS="$(prompt "APP_DB_SCHEMA_SYS" "public")"
  export APP_DB_SCHEMA_PB="$(prompt "APP_DB_SCHEMA_PB" "public")"
  export APP_DB_SCHEMA_IMAGELOG="$(prompt "APP_DB_SCHEMA_IMAGELOG" "public")"

  read -r -p "ImageLog JDBC URL (empty = use primary pool) []: " img_url || true
  export APP_DATASOURCE_IMAGELOG_URL="${img_url:-}"
  if [[ -n "${APP_DATASOURCE_IMAGELOG_URL}" ]]; then
    export APP_DATASOURCE_IMAGELOG_USERNAME="$(prompt "ImageLog JDBC user" "$db_user")"
    export APP_DATASOURCE_IMAGELOG_PASSWORD="$(prompt "ImageLog JDBC password" "$db_password")"
  else
    export APP_DATASOURCE_IMAGELOG_USERNAME=""
    export APP_DATASOURCE_IMAGELOG_PASSWORD=""
  fi

  local def_cors="http://127.0.0.1:${FRONTEND_PORT},http://localhost:${FRONTEND_PORT}"
  export CORS_ALLOWED_ORIGINS="$(prompt "CORS_ALLOWED_ORIGINS (comma-separated UI origins)" "$def_cors")"

  write_env_file "$ENV_FILE"
}

cmd_start() {
  ensure_dirs
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Missing $ENV_FILE — run: $0 configure" >&2
    exit 1
  fi
  # shellcheck disable=SC1090
  set -a
  source "$ENV_FILE"
  set +a

  if [[ -f "$RUN_DIR/backend.pid" ]] && kill -0 "$(cat "$RUN_DIR/backend.pid")" 2>/dev/null; then
    echo "Backend already running (pid $(cat "$RUN_DIR/backend.pid"))"
  else
    nohup java ${JAVA_OPTS:-} -jar "$BACKEND_JAR" >>"$LOG_DIR/backend.log" 2>&1 &
    echo $! >"$RUN_DIR/backend.pid"
    echo "Backend started pid=$(cat "$RUN_DIR/backend.pid") port=${SERVER_PORT:-9200}"
    sleep 2
  fi

  if [[ -f "$RUN_DIR/frontend.pid" ]] && kill -0 "$(cat "$RUN_DIR/frontend.pid")" 2>/dev/null; then
    echo "Frontend already running (pid $(cat "$RUN_DIR/frontend.pid"))"
  else
    export PORT="${FRONTEND_PORT:-3001}"
    nohup java ${JAVA_OPTS:-} -jar "$STATIC_JAR" "$WWW_DIR" "$PORT" >>"$LOG_DIR/frontend.log" 2>&1 &
    echo $! >"$RUN_DIR/frontend.pid"
    echo "Frontend started pid=$(cat "$RUN_DIR/frontend.pid") port=$PORT"
  fi
  echo "Logs: $LOG_DIR"
}

cmd_stop() {
  for name in backend frontend; do
    local f="$RUN_DIR/${name}.pid"
    if [[ -f "$f" ]]; then
      local pid
      pid="$(cat "$f")"
      if kill -0 "$pid" 2>/dev/null; then
        kill "$pid" && echo "Stopped $name (pid $pid)" || true
      fi
      rm -f "$f"
    fi
  done
}

cmd_status() {
  echo "=== Status ==="
  for name in backend frontend; do
    local f="$RUN_DIR/${name}.pid"
    if [[ -f "$f" ]]; then
      local pid
      pid="$(cat "$f")"
      if kill -0 "$pid" 2>/dev/null; then
        echo "$name: running pid=$pid"
      else
        echo "$name: stale pid file"
      fi
    else
      echo "$name: not started (no pid file)"
    fi
  done
  [[ -f "$ENV_FILE" ]] && echo "Env: $ENV_FILE" || echo "Env: not configured"
}

cmd_all() {
  if ! cmd_check; then
    read -r -p "Check reported issues. Continue anyway? [y/N]: " c || true
    [[ "$(lc "${c:-}")" == "y" ]] || exit 1
  fi
  read -r -p "Run DB setup now? [y/N]: " rdb || true
  if [[ "$(lc "${rdb:-}")" == "y" ]]; then
    cmd_db
  fi
  cmd_configure
  read -r -p "Start backend + frontend now? [Y/n]: " rst || true
  if [[ "$(lc "${rst:-y}")" != "n" ]]; then
    sleep 1
    cmd_start
  fi
  echo ""
  echo "Done. Next: source $ENV_FILE && ... or ./install-offline.sh start"
  echo "README: $BUNDLE_ROOT/README-OFFLINE.md"
}

usage() {
  echo "Usage: $0 check|db|configure|start|stop|status|all"
  exit 1
}

main() {
  local sub="${1:-}"
  [[ -n "$sub" ]] || usage
  case "$(lc "$sub")" in
    check) cmd_check ;;
    db) cmd_db ;;
    configure) cmd_configure ;;
    start) cmd_start ;;
    stop) cmd_stop ;;
    status) cmd_status ;;
    all) cmd_all ;;
    *) usage ;;
  esac
}

main "${1:-}"
