#!/usr/bin/env bash
#
# LogMng — single offline installer & launcher (no npm/mvn/internet on this host).
# Run from the root of the extracted offline bundle (same directory as bin/, db/).
#
# Usage: ./install-offline.sh check|db|configure|start|stop|status|all|start-frontend|stop-frontend
#
# Java: if `java` is not on PATH, set either
#   export JAVA_HOME=/path/to/jdk-17
#   export JAVA_CMD=/path/to/jdk-17/bin/java
# or answer the java path prompt in `configure` (saved to var/logmng.env).
#
# psql: only needed when you run ./install-offline.sh db (or all with DB=yes) on THIS host.
#       App start (configure/start) does not need psql if the database is already provisioned.
#
# Bundled psql: if tools/psql-deb/*.deb exist (Debian bookworm amd64 client), db step tries
#   dpkg -i as root/sudo when psql is missing. Set SKIP_BUNDLE_PSQL=1 to disable.
#
set -euo pipefail

BUNDLE_ROOT="$(cd "$(dirname "$0")" && pwd)"
VAR_DIR="$BUNDLE_ROOT/var"
LOG_DIR="$VAR_DIR/log"
RUN_DIR="$VAR_DIR/run"
ENV_FILE="$VAR_DIR/logmng.env"

BACKEND_JAR="$BUNDLE_ROOT/bin/backend/logmng-backend-1.0.0.jar"
STATIC_JAR="$BUNDLE_ROOT/bin/frontend/logmng-static-server-1.0.0.jar"
WWW_DIR="$BUNDLE_ROOT/bin/frontend/www"
DB_SETUP="$BUNDLE_ROOT/db/setup.sh"

lc() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

# Sets JAVA_BIN for backend/static-server processes. Honors JAVA_CMD, then PATH java, then JAVA_HOME.
resolve_java() {
  if [[ -n "${JAVA_CMD:-}" ]]; then
    if [[ -x "$JAVA_CMD" || -f "$JAVA_CMD" ]]; then
      JAVA_BIN="$JAVA_CMD"
      return 0
    fi
    echo "[WARN] JAVA_CMD is set but not executable: $JAVA_CMD" >&2
  fi
  if command -v java >/dev/null 2>&1; then
    JAVA_BIN="$(command -v java)"
    return 0
  fi
  if [[ -n "${JAVA_HOME:-}" && -x "$JAVA_HOME/bin/java" ]]; then
    JAVA_BIN="$JAVA_HOME/bin/java"
    return 0
  fi
  JAVA_BIN=""
  return 1
}

# Install bundled .deb PostgreSQL client when psql is missing (Debian/Ubuntu + dpkg only).
ensure_psql_from_bundle() {
  if command -v psql >/dev/null 2>&1; then
    return 0
  fi
  if [[ "${SKIP_BUNDLE_PSQL:-0}" == "1" ]]; then
    return 1
  fi
  local d="$BUNDLE_ROOT/tools/psql-deb"
  shopt -s nullglob
  local deb=( "$d"/*.deb )
  shopt -u nullglob
  if [[ ${#deb[@]} -eq 0 ]]; then
    return 1
  fi
  if ! command -v dpkg >/dev/null 2>&1; then
    echo "[INFO] Bundled .deb packages are present but dpkg was not found — use your OS postgresql client (e.g. RPM-based distros)." >&2
    return 1
  fi
  echo "psql not found — installing bundled packages from tools/psql-deb/ (requires root or sudo) ..."
  run_pkg_as_root() {
    if [[ "$(id -u)" -eq 0 ]]; then
      "$@"
    elif command -v sudo >/dev/null 2>&1; then
      sudo "$@"
    else
      echo "Root or sudo is required to install .deb files. Install postgresql-client manually." >&2
      return 1
    fi
  }
  local ordered=()
  local f
  for f in "$d"/postgresql-client-common_*.deb; do [[ -f "$f" ]] && ordered+=( "$f" ); done
  for f in "$d"/libpq5_*.deb; do [[ -f "$f" ]] && ordered+=( "$f" ); done
  for f in "$d"/postgresql-client-*.deb; do [[ -f "$f" ]] && ordered+=( "$f" ); done
  for f in "${deb[@]}"; do
    local seen=0
    local o
    for o in "${ordered[@]}"; do [[ "$f" == "$o" ]] && seen=1 && break; done
    [[ "$seen" -eq 0 ]] && ordered+=( "$f" )
  done
  if ! run_pkg_as_root dpkg -i "${ordered[@]}"; then
    echo "[WARN] dpkg -i failed — install missing dependencies from the same OS release (offline mirror) or add psql to PATH." >&2
    echo "       See tools/psql-deb/README.txt and README-OFFLINE.md." >&2
    return 1
  fi
  command -v psql >/dev/null 2>&1
}

prompt() {
  local label="$1"
  local def="$2"
  local val
  read -r -p "${label} [${def}]: " val || true
  if [[ -z "${val}" ]]; then
    echo "$def"
  else
    echo "$val"
  fi
}

prompt_secret() {
  local label="$1"
  local val
  read -r -s -p "${label}: " val || true
  echo ""
  echo "${val:-}"
}

ensure_dirs() {
  mkdir -p "$LOG_DIR" "$RUN_DIR"
}

write_env_file() {
  local path="$1"
  umask 077
  cat >"$path" <<EOF
# Generated by install-offline.sh — contains secrets.
export SERVER_PORT="${SERVER_PORT}"
export SPRING_DATASOURCE_URL="${SPRING_DATASOURCE_URL}"
export SPRING_DATASOURCE_USERNAME="${SPRING_DATASOURCE_USERNAME}"
export SPRING_DATASOURCE_PASSWORD="${SPRING_DATASOURCE_PASSWORD}"
export APP_DB_SCHEMA_SYS="${APP_DB_SCHEMA_SYS}"
export APP_DB_SCHEMA_PB="${APP_DB_SCHEMA_PB}"
export APP_DB_SCHEMA_IMAGELOG="${APP_DB_SCHEMA_IMAGELOG}"
export APP_DATASOURCE_IMAGELOG_URL="${APP_DATASOURCE_IMAGELOG_URL:-}"
export APP_DATASOURCE_IMAGELOG_USERNAME="${APP_DATASOURCE_IMAGELOG_USERNAME:-}"
export APP_DATASOURCE_IMAGELOG_PASSWORD="${APP_DATASOURCE_IMAGELOG_PASSWORD:-}"
export CORS_ALLOWED_ORIGINS="${CORS_ALLOWED_ORIGINS}"
export FRONTEND_PORT="${FRONTEND_PORT}"
export LOGMNG_API_BASE_URL="${LOGMNG_API_BASE_URL:-}"
# AES-256 암·복호화 (LogDbService/CryptoUtil). 운영에서는 반드시 고유 키(UTF-8 32바이트 권장).
export ENCRYPTION_KEY="${ENCRYPTION_KEY}"
export DECRYPTION_ENABLED="${DECRYPTION_ENABLED:-true}"
export AUTO_DECRYPT_ON_KEYWORD_SEARCH="${AUTO_DECRYPT_ON_KEYWORD_SEARCH:-true}"
export FAILURE_HANDLING="${FAILURE_HANDLING:-fallback}"
EOF
  if [[ -n "${JAVA_CMD_LINE:-}" ]]; then
    printf 'export JAVA_CMD="%s"\n' "${JAVA_CMD_LINE//\"/\\\"}" >>"$path"
  fi
  chmod 600 "$path"
  echo "Wrote $path (mode 600)"
}

cmd_check() {
  echo "=== Offline bundle check ==="
  echo "Root: $BUNDLE_ROOT"
  local ok=1
  resolve_java || true
  if [[ -z "${JAVA_BIN:-}" ]]; then
    echo "[FAIL] java not found on PATH and JAVA_HOME/bin/java missing."
    echo "      Fix: export JAVA_HOME=/path/to/jdk-17   (then re-run check)"
    echo "      or:  export JAVA_CMD=/path/to/jdk-17/bin/java"
    echo "      or:  ./install-offline.sh configure — java path prompt saves JAVA_CMD into var/logmng.env"
    ok=0
  else
    echo "[OK] java: $JAVA_BIN"
    "$JAVA_BIN" -version 2>&1 | head -1 || true
  fi
  if ! command -v psql >/dev/null 2>&1; then
    echo "[WARN] psql not on PATH — required for ./install-offline.sh db or all (DB on this host)."
    echo "       If tools/psql-deb/*.deb exist, the db step will try sudo dpkg -i (Debian/Ubuntu)."
    echo "       Else: Debian/Ubuntu postgresql-client | RHEL: postgresql (see README-OFFLINE.md)."
    echo "       Skip DB step if schema was applied elsewhere."
  else
    echo "[OK] psql: $(command -v psql)"
  fi
  [[ -f "$BACKEND_JAR" ]] && echo "[OK] backend JAR" || { echo "[FAIL] missing $BACKEND_JAR"; ok=0; }
  [[ -f "$STATIC_JAR" ]] && echo "[OK] static server JAR" || { echo "[FAIL] missing $STATIC_JAR"; ok=0; }
  [[ -f "$WWW_DIR/index.html" ]] && echo "[OK] frontend www/index.html" || { echo "[FAIL] missing $WWW_DIR/index.html"; ok=0; }
  [[ -f "$DB_SETUP" ]] && echo "[OK] db/setup.sh" || { echo "[FAIL] missing $DB_SETUP"; ok=0; }
  return $((1 - ok))
}

cmd_db() {
  echo "=== Database setup (bundled db/setup.sh) ==="
  if [[ ! -f "$DB_SETUP" ]]; then
    echo "Missing $DB_SETUP" >&2
    exit 1
  fi
  if [[ "$(uname -s)" != "Linux" ]]; then
    echo "Warning: expected Linux server (found: $(uname -s))"
  fi
  echo ""
  echo "  1) Full DDL + migrations + init-data (new DB)"
  echo "  2) sys_only (PB already in SCHEMA_PB; new SCHEMA_SYS only)"
  echo "  3) Skip DB script (already provisioned)"
  echo ""
  local dchoice
  read -r -p "Select [1-3]: " dchoice || true
  if [[ "$dchoice" == "3" ]]; then
    echo "Skipped."
    return 0
  fi
  if ! command -v psql >/dev/null 2>&1; then
    ensure_psql_from_bundle || true
  fi
  if ! command -v psql >/dev/null 2>&1; then
    echo "psql not found on PATH. Install postgresql-client (or add psql to PATH), use bundled tools/psql-deb on Debian/Ubuntu with sudo, or run DDL from another host using bundle db/*.sql" >&2
    exit 1
  fi
  export DB_SUPERUSER="$(prompt "PostgreSQL superuser" "postgres")"
  echo "Superuser password (empty if peer/trust):"
  local sp
  sp="$(prompt_secret "PGPASSWORD_SUPER")"
  [[ -n "$sp" ]] && export PGPASSWORD_SUPER="$sp"

  export DB_HOST="$(prompt "DB host" "localhost")"
  export DB_PORT="$(prompt "DB port" "5432")"
  export DB_NAME="$(prompt "Database name (A)" "logmng")"
  export DB_USER="$(prompt "App DB user" "logmng")"
  export DB_PASSWORD="$(prompt "App DB password" "logmng123")"
  export DB_A_NAME="$DB_NAME"
  export DB_B_NAME="$(prompt "ImageLog DB (B, same as A for single DB)" "$DB_NAME")"
  export SCHEMA_SYS="$(prompt "SCHEMA_SYS" "public")"
  export SCHEMA_PB="$(prompt "SCHEMA_PB" "public")"
  export SCHEMA_IMAGELOG="$(prompt "SCHEMA_IMAGELOG (on B)" "public")"

  if [[ "$dchoice" == "2" ]]; then
    echo ""
    echo "sys_only: PB DDL skipped. See README-OFFLINE.md / DB_SETUP_GUIDE if unsure."
    read -r -p "Continue? [y/N]: " ok || true
    [[ "$(lc "${ok:-}")" == "y" ]] || exit 1
    export SETUP_MODE=sys_only
  else
    export SETUP_MODE=full
  fi

  (cd "$BUNDLE_ROOT/db" && bash ./setup.sh)
  echo "DB step done."
}

cmd_configure() {
  echo "=== Application environment ($ENV_FILE) ==="
  ensure_dirs
  local db_host db_port db_name db_user db_password
  db_host="$(prompt "DB host (for JDBC)" "localhost")"
  db_port="$(prompt "DB port" "5432")"
  db_name="$(prompt "Database name (primary A)" "logmng")"
  db_user="$(prompt "JDBC username" "logmng")"
  db_password="$(prompt "JDBC password" "logmng123")"

  export SERVER_PORT="$(prompt "Backend HTTP port" "9200")"
  export FRONTEND_PORT="$(prompt "Frontend static port" "3001")"
  export SPRING_DATASOURCE_URL="jdbc:postgresql://${db_host}:${db_port}/${db_name}"
  export SPRING_DATASOURCE_USERNAME="$db_user"
  export SPRING_DATASOURCE_PASSWORD="$db_password"
  export APP_DB_SCHEMA_SYS="$(prompt "APP_DB_SCHEMA_SYS" "public")"
  export APP_DB_SCHEMA_PB="$(prompt "APP_DB_SCHEMA_PB" "public")"
  export APP_DB_SCHEMA_IMAGELOG="$(prompt "APP_DB_SCHEMA_IMAGELOG" "public")"

  read -r -p "ImageLog JDBC URL (empty = use primary pool) []: " img_url || true
  export APP_DATASOURCE_IMAGELOG_URL="${img_url:-}"
  if [[ -n "${APP_DATASOURCE_IMAGELOG_URL}" ]]; then
    export APP_DATASOURCE_IMAGELOG_USERNAME="$(prompt "ImageLog JDBC user" "$db_user")"
    export APP_DATASOURCE_IMAGELOG_PASSWORD="$(prompt "ImageLog JDBC password" "$db_password")"
  else
    export APP_DATASOURCE_IMAGELOG_USERNAME=""
    export APP_DATASOURCE_IMAGELOG_PASSWORD=""
  fi

  local def_cors="http://127.0.0.1:${FRONTEND_PORT},http://localhost:${FRONTEND_PORT}"
  export CORS_ALLOWED_ORIGINS="$(prompt "CORS_ALLOWED_ORIGINS (comma-separated UI origins)" "$def_cors")"

  local def_api="http://127.0.0.1:${SERVER_PORT}/api"
  echo ""
  echo "브라우저가 호출할 백엔드 API 베이스 URL (정적 UI용; 비우면 빌드 시 REACT_APP 값 또는 localhost 기본)."
  export LOGMNG_API_BASE_URL="$(prompt "LOGMNG_API_BASE_URL (empty = build default)" "$def_api")"

  echo ""
  echo "암·복호화 키 (AES-256, UTF-8로 32바이트 권장). 운영은 임의 32바이트 이상으로 변경하세요."
  export ENCRYPTION_KEY="$(prompt "ENCRYPTION_KEY" "12345678901234567890123456789012")"
  export DECRYPTION_ENABLED="$(prompt "DECRYPTION_ENABLED (true/false)" "true")"
  export AUTO_DECRYPT_ON_KEYWORD_SEARCH="$(prompt "AUTO_DECRYPT_ON_KEYWORD_SEARCH (true/false)" "true")"
  export FAILURE_HANDLING="$(prompt "FAILURE_HANDLING (fallback|skip|error)" "fallback")"

  echo ""
  echo "Java: if PATH에 java가 없으면 JDK 설치 경로의 bin/java 전체 경로를 입력하세요."
  JAVA_CMD_LINE="$(prompt "java full path (empty if java is already on PATH)" "")"
  export JAVA_CMD_LINE

  write_env_file "$ENV_FILE"
}

cmd_start() {
  ensure_dirs
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Missing $ENV_FILE — run: $0 configure" >&2
    exit 1
  fi
  # shellcheck disable=SC1090
  set -a
  source "$ENV_FILE"
  set +a

  resolve_java || true
  if [[ -z "${JAVA_BIN:-}" ]]; then
    echo "Cannot find java. Set JAVA_HOME, or JAVA_CMD in $ENV_FILE, or PATH." >&2
    exit 1
  fi

  if [[ -f "$RUN_DIR/backend.pid" ]] && kill -0 "$(cat "$RUN_DIR/backend.pid")" 2>/dev/null; then
    echo "Backend already running (pid $(cat "$RUN_DIR/backend.pid"))"
  else
    nohup "$JAVA_BIN" ${JAVA_OPTS:-} -jar "$BACKEND_JAR" >>"$LOG_DIR/backend.log" 2>&1 &
    echo $! >"$RUN_DIR/backend.pid"
    echo "Backend started pid=$(cat "$RUN_DIR/backend.pid") port=${SERVER_PORT:-9200}"
    sleep 2
  fi

  if [[ -f "$RUN_DIR/frontend.pid" ]] && kill -0 "$(cat "$RUN_DIR/frontend.pid")" 2>/dev/null; then
    echo "Frontend already running (pid $(cat "$RUN_DIR/frontend.pid"))"
  else
    export PORT="${FRONTEND_PORT:-3001}"
    nohup "$JAVA_BIN" ${JAVA_OPTS:-} -jar "$STATIC_JAR" "$WWW_DIR" "$PORT" >>"$LOG_DIR/frontend.log" 2>&1 &
    echo $! >"$RUN_DIR/frontend.pid"
    echo "Frontend started pid=$(cat "$RUN_DIR/frontend.pid") port=$PORT"
  fi
  echo "Logs: $LOG_DIR"
}

# 정적 UI만 기동 (백엔드 없음). var/logmng.env 가 있으면 로드해 FRONTEND_PORT·LOGMNG_API_BASE_URL·JAVA_CMD 반영.
cmd_start_frontend() {
  ensure_dirs
  if [[ -f "$ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    set -a
    source "$ENV_FILE"
    set +a
  else
    echo "[INFO] No $ENV_FILE — using shell env only (FRONTEND_PORT, LOGMNG_API_BASE_URL, JAVA_HOME, PATH)." >&2
  fi
  resolve_java || true
  if [[ -z "${JAVA_BIN:-}" ]]; then
    echo "Cannot find java. Set JAVA_HOME, JAVA_CMD, PATH, or run: $0 configure" >&2
    exit 1
  fi
  if [[ ! -f "$STATIC_JAR" || ! -f "$WWW_DIR/index.html" ]]; then
    echo "Missing static UI: $STATIC_JAR or $WWW_DIR/index.html" >&2
    exit 1
  fi
  if [[ -f "$RUN_DIR/frontend.pid" ]] && kill -0 "$(cat "$RUN_DIR/frontend.pid")" 2>/dev/null; then
    echo "Frontend already running (pid $(cat "$RUN_DIR/frontend.pid"))"
    return 0
  fi
  export PORT="${FRONTEND_PORT:-3001}"
  nohup "$JAVA_BIN" ${JAVA_OPTS:-} -jar "$STATIC_JAR" "$WWW_DIR" "$PORT" >>"$LOG_DIR/frontend.log" 2>&1 &
  echo $! >"$RUN_DIR/frontend.pid"
  echo "Frontend only: pid=$(cat "$RUN_DIR/frontend.pid") port=$PORT (backend not started)"
  echo "Log: $LOG_DIR/frontend.log"
}

cmd_stop_frontend() {
  local f="$RUN_DIR/frontend.pid"
  if [[ -f "$f" ]]; then
    local pid
    pid="$(cat "$f")"
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" && echo "Stopped frontend (pid $pid)" || true
    else
      echo "Frontend: stale pid file"
    fi
    rm -f "$f"
  else
    echo "Frontend: not started (no pid file)"
  fi
}

cmd_stop() {
  for name in backend frontend; do
    local f="$RUN_DIR/${name}.pid"
    if [[ -f "$f" ]]; then
      local pid
      pid="$(cat "$f")"
      if kill -0 "$pid" 2>/dev/null; then
        kill "$pid" && echo "Stopped $name (pid $pid)" || true
      fi
      rm -f "$f"
    fi
  done
}

cmd_status() {
  echo "=== Status ==="
  for name in backend frontend; do
    local f="$RUN_DIR/${name}.pid"
    if [[ -f "$f" ]]; then
      local pid
      pid="$(cat "$f")"
      if kill -0 "$pid" 2>/dev/null; then
        echo "$name: running pid=$pid"
      else
        echo "$name: stale pid file"
      fi
    else
      echo "$name: not started (no pid file)"
    fi
  done
  [[ -f "$ENV_FILE" ]] && echo "Env: $ENV_FILE" || echo "Env: not configured"
}

cmd_all() {
  if ! cmd_check; then
    read -r -p "Check reported issues. Continue anyway? [y/N]: " c || true
    [[ "$(lc "${c:-}")" == "y" ]] || exit 1
  fi
  read -r -p "Run DB setup now? [y/N]: " rdb || true
  if [[ "$(lc "${rdb:-}")" == "y" ]]; then
    cmd_db
  fi
  cmd_configure
  read -r -p "Start backend + frontend now? [Y/n]: " rst || true
  if [[ "$(lc "${rst:-y}")" != "n" ]]; then
    sleep 1
    cmd_start
  fi
  echo ""
  echo "Done. Next: source $ENV_FILE && ... or ./install-offline.sh start"
  echo "README: $BUNDLE_ROOT/README-OFFLINE.md"
}

usage() {
  echo "Usage: $0 check|db|configure|start|stop|status|all|start-frontend|stop-frontend"
  exit 1
}

main() {
  local sub="${1:-}"
  [[ -n "$sub" ]] || usage
  case "$(lc "$sub")" in
    check) cmd_check ;;
    db) cmd_db ;;
    configure) cmd_configure ;;
    start) cmd_start ;;
    stop) cmd_stop ;;
    status) cmd_status ;;
    all) cmd_all ;;
    start-frontend|frontend-start) cmd_start_frontend ;;
    stop-frontend|frontend-stop) cmd_stop_frontend ;;
    *) usage ;;
  esac
}

main "${1:-}"
