#!/usr/bin/env bash
# Interactive Linux helper: PostgreSQL setup (full or sys_only) + optional app env file.
# Usage: from repo root — ./scripts/install_linux.sh
# Requires: psql, bash 4+ (for ${var,,}); PostgreSQL reachable on this host.
#
# For a full offline bundle (JARs + db + single install/start tool on the server), use
#   ./scripts/build-offline-bundle.sh
# and on the air-gapped host: ./install-offline.sh all

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DB_SETUP_SH="$REPO_ROOT/backend/src/main/resources/db/setup.sh"

if [[ ! -f "$DB_SETUP_SH" ]]; then
  echo "setup.sh not found: $DB_SETUP_SH" >&2
  exit 1
fi

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "이 스크립트는 Linux 환경을 대상으로 합니다 (현재: $(uname -s))." >&2
  read -r -p "그래도 계속할까요? [y/N]: " cont || true
  if [[ "${cont,,}" != "y" ]]; then
    exit 1
  fi
fi

prompt() {
  local label="$1"
  local def="$2"
  local val
  read -r -p "${label} [${def}]: " val || true
  if [[ -z "${val}" ]]; then
    echo "$def"
  else
    echo "$val"
  fi
}

prompt_secret() {
  local label="$1"
  local val
  read -r -s -p "${label}: " val || true
  echo ""
  if [[ -z "${val}" ]]; then
    echo ""
  else
    echo "$val"
  fi
}

write_env_file() {
  local path="$1"
  cat >"$path" <<EOF
# Generated by scripts/install_linux.sh — do not commit secrets. Use systemd EnvironmentFile or export before java -jar.
# Primary (A)
export SPRING_DATASOURCE_URL="${SPRING_DATASOURCE_URL}"
export SPRING_DATASOURCE_USERNAME="${SPRING_DATASOURCE_USERNAME}"
export SPRING_DATASOURCE_PASSWORD="${SPRING_DATASOURCE_PASSWORD}"
# Schema search_path (Hikari init — must match DB DDL placement)
export APP_DB_SCHEMA_SYS="${APP_DB_SCHEMA_SYS}"
export APP_DB_SCHEMA_PB="${APP_DB_SCHEMA_PB}"
export APP_DB_SCHEMA_IMAGELOG="${APP_DB_SCHEMA_IMAGELOG}"
# ImageLog pool (optional; empty = reuse primary)
export APP_DATASOURCE_IMAGELOG_URL="${APP_DATASOURCE_IMAGELOG_URL}"
export APP_DATASOURCE_IMAGELOG_USERNAME="${APP_DATASOURCE_IMAGELOG_USERNAME}"
export APP_DATASOURCE_IMAGELOG_PASSWORD="${APP_DATASOURCE_IMAGELOG_PASSWORD}"
EOF
  echo "Wrote: $path"
}

echo ""
echo "=== LogMng Linux 설치 도구 ==="
echo "저장소: $REPO_ROOT"
echo ""
echo "  1) DB 전체 설정 (setup.sh — PB + 시스템 + 활동로그 + ImageLog + 마이그레이션 + init-data)"
echo "  2) 시스템 스키마만 추가 (SETUP_MODE=sys_only — PB DDL·init-data 생략, SCHEMA_SYS 신규)"
echo "  3) 애플리케이션용 export 문만 생성 (파일 저장 또는 화면 출력)"
echo "  4) 종료"
echo ""
read -r -p "선택 (1-4): " choice

if [[ "$choice" == "4" ]]; then
  exit 0
fi

echo ""
DB_SUPERUSER="$(prompt "PostgreSQL 슈퍼유저" "postgres")"
DB_HOST="$(prompt "DB 호스트" "localhost")"
DB_PORT="$(prompt "DB 포트" "5432")"
DB_NAME="$(prompt "데이터베이스 이름 (A)" "logmng")"
DB_USER="$(prompt "애플리케이션 DB 사용자" "logmng")"
DB_PASSWORD="$(prompt "애플리케이션 DB 비밀번호" "logmng123")"
echo "슈퍼유저 비밀번호(선택, 로컬 trust면 Enter):"
PGPASS_SUPER="$(prompt_secret "PGPASSWORD_SUPER")"

SCHEMA_SYS="$(prompt "시스템 스키마 (SCHEMA_SYS / APP_DB_SCHEMA_SYS)" "public")"
SCHEMA_PB="$(prompt "PB FEP 스키마 (SCHEMA_PB / APP_DB_SCHEMA_PB)" "public")"
DB_B_NAME="$(prompt "ImageLog DB 이름 (B, 단일 DB면 A와 동일)" "$DB_NAME")"
SCHEMA_IMAGELOG="$(prompt "ImageLog 스키마 (B)" "public")"

export DB_SUPERUSER DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD
export DB_A_NAME="$DB_NAME" DB_B_NAME="$DB_B_NAME"
export SCHEMA_SYS SCHEMA_PB SCHEMA_IMAGELOG
if [[ -n "$PGPASS_SUPER" ]]; then
  export PGPASSWORD_SUPER="$PGPASS_SUPER"
fi

SPRING_DATASOURCE_URL="jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_A_NAME}"
SPRING_DATASOURCE_USERNAME="$DB_USER"
SPRING_DATASOURCE_PASSWORD="$DB_PASSWORD"
APP_DB_SCHEMA_SYS="$SCHEMA_SYS"
APP_DB_SCHEMA_PB="$SCHEMA_PB"
APP_DB_SCHEMA_IMAGELOG="$SCHEMA_IMAGELOG"
APP_DATASOURCE_IMAGELOG_URL=""
APP_DATASOURCE_IMAGELOG_USERNAME=""
APP_DATASOURCE_IMAGELOG_PASSWORD=""

if [[ "$choice" == "3" ]]; then
  echo ""
  read -r -p "ImageLog 전용 JDBC URL (비우면 단일 DB 폴백) []: " img_url || true
  APP_DATASOURCE_IMAGELOG_URL="${img_url:-}"
  if [[ -n "$APP_DATASOURCE_IMAGELOG_URL" ]]; then
    APP_DATASOURCE_IMAGELOG_USERNAME="$(prompt "ImageLog DB 사용자" "$DB_USER")"
    APP_DATASOURCE_IMAGELOG_PASSWORD="$(prompt "ImageLog DB 비밀번호" "$DB_PASSWORD")"
  fi
  OUT_DEFAULT="$REPO_ROOT/backend/.env.logmng.generated"
  read -r -p "파일로 저장할 경로 [${OUT_DEFAULT}]: " out_path || true
  out_path="${out_path:-$OUT_DEFAULT}"
  write_env_file "$out_path"
  echo ""
  echo "--- 동일 내용 (검토용) ---"
  cat "$out_path"
  exit 0
fi

if [[ "$choice" == "2" ]]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "주의 (sys_only)"
  echo "  • PB 테이블(pb_send 등)은 이미 스키마 \"${SCHEMA_PB}\" 에 있다고 가정합니다."
  echo "  • 시스템 테이블(app_user, search_history 등)이 이미 \"${SCHEMA_PB}\" 또는 public 에 있다면,"
  echo "    \"${SCHEMA_SYS}\" 에 DDL을 적용하면 빈 복제 테이블이 생길 수 있고,"
  echo "    APP_DB_SCHEMA_SYS=${SCHEMA_SYS} 로 앱을 띄우면 데이터가 안 보일 수 있습니다."
  echo "  • 그 경우 설정으로 APP_DB_SCHEMA_SYS=APP_DB_SCHEMA_PB=logmng 처럼 동일 스키마를 쓰거나,"
  echo "    DBA 마이그레이션으로 테이블을 한 스키마로 모은 뒤 적용하세요."
  echo "  • 자세한 설명: backend/DB_SETUP_GUIDE.md"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  read -r -p "위 내용을 이해했고 계속합니다 [y/N]: " ok || true
  if [[ "${ok,,}" != "y" ]]; then
    exit 1
  fi
  export SETUP_MODE=sys_only
fi

if [[ "$choice" == "1" ]]; then
  export SETUP_MODE=full
fi

echo ""
echo "setup.sh 실행: $DB_SETUP_SH"
bash "$DB_SETUP_SH"

echo ""
read -r -p "애플리케이션용 export 파일을 생성할까요? [y/N]: " gen || true
if [[ "${gen,,}" == "y" ]]; then
  read -r -p "ImageLog 전용 JDBC URL (비우면 단일 DB) []: " img_url || true
  APP_DATASOURCE_IMAGELOG_URL="${img_url:-}"
  if [[ -n "$APP_DATASOURCE_IMAGELOG_URL" ]]; then
    APP_DATASOURCE_IMAGELOG_USERNAME="$(prompt "ImageLog DB 사용자" "$DB_USER")"
    APP_DATASOURCE_IMAGELOG_PASSWORD="$(prompt "ImageLog DB 비밀번호" "$DB_PASSWORD")"
  fi
  OUT_DEFAULT="$REPO_ROOT/backend/.env.logmng.generated"
  read -r -p "저장 경로 [${OUT_DEFAULT}]: " out_path || true
  out_path="${out_path:-$OUT_DEFAULT}"
  write_env_file "$out_path"
  echo "systemd 예: EnvironmentFile=$out_path"
  echo "또는: set -a && source $out_path && set +a && java -jar ..."
fi

echo ""
echo "완료. 백엔드는 Spring이 읽는 키 이름과 맞추려면:"
echo "  spring.datasource.url → 보통 SPRING_DATASOURCE_URL 환경 변수로 덮어씀"
echo "  자세히: docs/contract.md, backend/src/main/resources/application.yml"
